import { Link, Outlet, createRootRoute, createRoute, createRouter } from "@tanstack/react-router";
import { Home } from "./pages/home";
import { dashboardSearch } from "./lib/permissions";
import { EmptyState } from "./components/ui/empty-state/empty-state";
import { Button } from "./components/ui/button/button";
export function DashboardNotFound() { return <main><EmptyState title="Page not found" description="That dashboard page does not exist." action={<Button render={<Link to="/home" />}>Return home</Button>} /></main>; }
const root = createRootRoute({ component: Outlet, notFoundComponent: DashboardNotFound });
function route<const T extends string>(path: T) { return createRoute({ getParentRoute: () => root, path, validateSearch: dashboardSearch, component: Home }); }
const routes = [route("/"), route("/home"), route("/notifications"), route("/admin/settings/alerts"), route("/admin/alerts/$record"), route("/workspaces/$ws/alerts/$record"), route("/admin"), route("/admin/users"), route("/admin/users/$record"), route("/admin/teams"), route("/admin/teams/$record"), route("/admin/projects"), route("/admin/projects/$record"), route("/admin/models"), route("/admin/models/new"), route("/admin/models/compare"), route("/admin/key-safety"), route("/admin/models/$record"), route("/admin/connections"), route("/admin/connections/$record"), route("/admin/providers"), route("/admin/providers/$record"), route("/admin/deployments"), route("/admin/deployments/$record"), route("/admin/routes/$record"), route("/admin/catalogs"), route("/admin/catalogs/$record"), route("/admin/limits"), route("/admin/settings"), route("/admin/settings/general"), route("/admin/settings/limits"), route("/admin/settings/privacy"), route("/admin/settings/email"), route("/admin/settings/sign-in"), route("/admin/policies"), route("/admin/cost-centers"), route("/admin/costs"), route("/admin/sso-groups"), route("/admin/oidc"), route("/admin/audit"), route("/admin/logs"), route("/admin/logs/session"), route("/admin/logs/$record"), route("/admin/pricing"), route("/admin/routing"), route("/workspaces/$ws"), route("/workspaces/$ws/keys"), route("/workspaces/$ws/keys/$record"), route("/workspaces/$ws/models"), route("/workspaces/$ws/models/compare"), route("/workspaces/$ws/models/$record"), route("/workspaces/$ws/logs"), route("/workspaces/$ws/session"), route("/workspaces/$ws/requests"), route("/workspaces/$ws/requests/$record"), route("/workspaces/$ws/costs"), route("/workspaces/$ws/settings"), route("/profile"), route("/invitations/accept")];
export const dashboardRouteTree = root.addChildren(routes);
export const router = createRouter({ routeTree: dashboardRouteTree });
declare module "@tanstack/react-router" { interface Register { router: typeof router } }
