{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "omg.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omg.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "omg.gatewaySelectorLabels" . | nindent 6 }}
{{- end }}
