// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { render, screen, waitFor, cleanup } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClientProvider } from "@tanstack/react-query";
import { createMemoryHistory, createRootRoute, createRoute, createRouter, RouterProvider, Outlet } from "@tanstack/react-router";
import type { ReactNode } from "react";
import { ActionProvider, Button, useAction, ApiScopeProvider, useApi, type Action } from "./ui";
import { DashboardNavigationProvider, ResourceLink } from "./navigation-link";
import { SettingsForm } from "./templates/settings-form";
import { Keys, MembersTable } from "../pages/workspace";
import { session, admin, auditor, team, grant, model, testClient } from "../lib/test-fixtures";
import { nameField } from "../lib/forms";
import { abortRequests } from "../lib/api";
function Open({ action }: { action: Action }) { const ask = useAction(); return <Button onClick={() => ask(action)}>Open action</Button>; }
function mount(node: ReactNode, client = testClient()) { return { client, ...render(<QueryClientProvider client={client}><ActionProvider>{node}</ActionProvider></QueryClientProvider>) }; }
beforeEach(() => { document.cookie = "omg_csrf=test-csrf; Path=/"; localStorage.clear(); sessionStorage.clear(); vi.stubGlobal("ResizeObserver", class { observe() {} unobserve() {} disconnect() {} }); Object.defineProperty(window, "matchMedia", { configurable: true, writable: true, value: () => ({ matches: false, addListener() {}, removeListener() {}, addEventListener() {}, removeEventListener() {}, dispatchEvent() { return false; } }) }); });
afterEach(() => { cleanup(); abortRequests(); vi.unstubAllGlobals(); vi.restoreAllMocks(); });
describe("real Bitop dialogs, keys and form lifecycles", () => {
  it("keeps one-time credentials out of both query/mutation caches and storage", async () => { const user = userEvent.setup(), token = "one-time-test-token", run = vi.fn().mockResolvedValue({ id: "key", token }), result = mount(<Open action={{ title: "Issue key", fields: [nameField], secretLabel: "Save your API key", run }} />); await user.click(screen.getByRole("button", { name: "Open action" })); await user.type(screen.getByRole("textbox", { name: /^Name/ }), "Client"); await user.click(screen.getByRole("button", { name: "Save" })); const input = await screen.findByRole("textbox", { name: "One-time token" }); expect((input as HTMLTextAreaElement).value).toBe(token); expect(result.client.getMutationCache().getAll()).toEqual([]); expect(JSON.stringify(result.client.getQueryCache().getAll().map(q => q.state.data))).not.toContain(token); expect(localStorage.length + sessionStorage.length).toBe(0); await user.click(screen.getByRole("button", { name: "I have saved it" })); await waitFor(() => expect(screen.queryByRole("dialog")).toBeNull()); expect(document.body.textContent).not.toContain(token); result.client.clear(); });
  it("protects dirty dialog values, then restores trigger focus on discard", async () => { const user = userEvent.setup(), run = vi.fn(), result = mount(<Open action={{ title: "Create resource", fields: [nameField], run }} />); const trigger = screen.getByRole("button", { name: "Open action" }); await user.click(trigger); await user.type(screen.getByRole("textbox", { name: /^Name/ }), "Unsaved"); await user.click(screen.getByRole("button", { name: "Cancel" })); await screen.findByRole("alertdialog", { name: "Leave without saving?" }); await user.click(screen.getByRole("button", { name: "Keep editing" })); expect((screen.getByRole("textbox", { name: /^Name/ }) as HTMLInputElement).value).toBe("Unsaved"); await user.click(screen.getByRole("button", { name: "Cancel" })); await user.click(await screen.findByRole("button", { name: "Discard changes" })); await waitFor(() => expect(screen.queryByRole("dialog")).toBeNull()); await waitFor(() => expect(document.activeElement).toBe(trigger)); expect(run).not.toHaveBeenCalled(); result.client.clear(); });
  it("aborts an in-flight action on scope unmount and never retains late plaintext", async () => { const user = userEvent.setup(); let signal: AbortSignal | undefined, resolve!: (result: unknown) => void; const run = vi.fn((_: unknown, s: AbortSignal) => { signal = s; return new Promise(r => { resolve = r; }); }); const result = mount(<Open action={{ title: "Issue", secretLabel: "Save token", run }} />); await user.click(screen.getByRole("button", { name: "Open action" })); await user.click(screen.getByRole("button", { name: "Save" })); expect(signal?.aborted).toBe(false); result.unmount(); expect(signal?.aborted).toBe(true); resolve({ token: "late-plaintext" }); await Promise.resolve(); expect(JSON.stringify(result.client.getQueryCache().getAll().map(q => q.state.data))).not.toContain("late-plaintext"); expect(result.client.getMutationCache().getAll()).toEqual([]); result.client.clear(); });
  it("validates forms before submitting and preserves server validation messages", async () => { const user = userEvent.setup(), run = vi.fn().mockRejectedValue(new Error("Pinned scope changed")), result = mount(<Open action={{ title: "Create", fields: [nameField], run }} />); await user.click(screen.getByRole("button", { name: "Open action" })); await user.click(screen.getByRole("button", { name: "Save" })); expect(run).not.toHaveBeenCalled(); expect(document.activeElement).toBe(screen.getByRole("textbox", { name: /^Name/ })); await user.type(screen.getByRole("textbox", { name: /^Name/ }), "Valid"); await user.click(screen.getByRole("button", { name: "Save" })); await screen.findByText("Pinned scope changed"); expect(run).toHaveBeenCalledOnce(); result.client.clear(); });
  it("offers shared-admin revoke but never rotation for another human", async () => { const user = userEvent.setup(), client = testClient(), key = { id: "key", name: "Other human", issued_to_user_id: "other", service_account_id: null, created_at: "2026-01-01T00:00:00Z", expires_at: "2099-01-01T00:00:00Z", revoked_at: null }; client.setQueryData(["api", undefined, "/api/v1/workspaces/team/models", "choices"], [grant]); client.setQueryData(["api", undefined, "/api/v1/workspaces/team/service-accounts", "choices"], []); client.setQueryData(["api", undefined, "/api/v1/workspaces/team/keys", "choices"], [key]); mount(<Keys session={admin} workspace={team} />, client); await user.click(screen.getByRole("button", { name: "Actions for Other human" })); expect(await screen.findByRole("menuitem", { name: "Revoke key…" })).toBeDefined(); expect(screen.queryByRole("menuitem", { name: "Rotate key…" })).toBeNull(); await user.click(screen.getByRole("menuitem", { name: "Revoke key…" })); await screen.findByRole("dialog", { name: "Revoke Other human?" }); expect(document.activeElement).not.toBe(screen.getByRole("button", { name: "Revoke key" })); client.clear(); });
  it("does not offer owner-role changes to a shared administrator", async () => { const user = userEvent.setup(), client = testClient(); client.setQueryData(["api", undefined, "/api/v1/workspaces/team/members", "choices"], [{ user_id: "owner", email: "owner@example.invalid", role: "owner", membership_source: "manual", grants: [{ role: "owner", source: "manual" }] }]); mount(<MembersTable path="/api/v1/workspaces/team/members" title="Members" canManageOwners={false} writable />, client); await user.click(screen.getByRole("button", { name: "Actions for owner@example.invalid" })); const change = await screen.findByRole("menuitem", { name: /^Set manual role…/ }); expect(change.getAttribute("aria-disabled")).toBe("true"); await user.click(change); expect(screen.queryByRole("dialog")).toBeNull(); client.clear(); });
  it("blocks route navigation for unsaved settings and supports cancel/proceed", async () => { const user = userEvent.setup(), client = testClient(), save = vi.fn().mockResolvedValue({ ok: true }), root = createRootRoute({ component: Outlet }); let router: ReturnType<typeof createRouter>; const first = createRoute({ getParentRoute: () => root, path: "/", component: () => <DashboardNavigationProvider search={{ page: "workspace-settings", ws: "team" }} navigate={() => void router.navigate({ to: "/profile" })}><SettingsForm fields={[{ ...nameField, value: "Original" }]} writable onSave={save} /><ResourceLink search={{ page: "profile" }}>Your profile</ResourceLink></DashboardNavigationProvider> }), second = createRoute({ getParentRoute: () => root, path: "/profile", component: () => <h1>Destination profile</h1> }); router = createRouter({ routeTree: root.addChildren([first, second]), history: createMemoryHistory({ initialEntries: ["/"] }) }); await router.load(); render(<QueryClientProvider client={client}><RouterProvider router={router} /></QueryClientProvider>); const input = await screen.findByRole("textbox", { name: /^Name/ }); await user.clear(input); await user.type(input, "Unsaved"); await user.click(screen.getByRole("link", { name: "Your profile" })); await screen.findByRole("alertdialog", { name: "Leave without saving?" }); await user.click(screen.getByRole("button", { name: "Keep editing" })); expect(router.state.location.pathname).toBe("/"); await user.click(screen.getByRole("link", { name: "Your profile" })); await user.click(await screen.findByRole("button", { name: "Leave without saving" })); await screen.findByRole("heading", { name: "Destination profile" }); expect(save).not.toHaveBeenCalled(); client.clear(); });
  it("isolates query caches by complete live capabilities and identity", async () => { const client = testClient(), fetch = vi.fn().mockImplementation(() => Promise.resolve(Response.json({ name: "current-authorized-record" }))); vi.stubGlobal("fetch", fetch); function Read() { const q = useApi<{ name: string }>("/api/v1/workspaces/team"); return <p>{q.data?.name ?? "Loading"}</p>; } const result = render(<QueryClientProvider client={client}><ApiScopeProvider session={admin}><Read /></ApiScopeProvider></QueryClientProvider>); await screen.findByText("current-authorized-record"); const old = client.getQueryCache().getAll()[0].queryKey; result.rerender(<QueryClientProvider client={client}><ApiScopeProvider session={{ ...auditor, user: { ...auditor.user, id: "another" } }}><Read /></ApiScopeProvider></QueryClientProvider>); await screen.findByText("current-authorized-record"); await waitFor(() => expect(fetch).toHaveBeenCalledTimes(2)); expect(client.getQueryCache().getAll().at(-1)?.queryKey).not.toEqual(old); client.clear(); });
});

describe("Create key dialog focus (finding #15)", () => {
  it("returns focus to the Create key button after Cancel and Escape", async () => {
    const user = userEvent.setup(), client = testClient(), path = "/api/v1/workspaces/team";
    client.setQueryData(["api", undefined, `${path}/keys`, "choices"], []); client.setQueryData(["api", undefined, `${path}/models`, "choices"], [grant]); client.setQueryData(["api", undefined, `${path}/service-accounts`, "choices"], []);
    client.setQueryData(["api", undefined, `${path}/policy`], { policy: null, effective: null, provenance: null });
    vi.stubGlobal("fetch", vi.fn().mockImplementation(() => Promise.resolve(Response.json({}))));
    mount(<DashboardNavigationProvider search={{ page: "keys", ws: "team" }} navigate={() => {}}><Keys session={session} workspace={team} /></DashboardNavigationProvider>, client);
    const trigger = screen.getByRole("button", { name: "Create key" });
    await user.click(trigger);
    await user.click(await screen.findByRole("button", { name: "Cancel" }));
    await waitFor(() => expect(document.activeElement).toBe(screen.getByRole("button", { name: "Create key" })));
    await user.click(screen.getByRole("button", { name: "Create key" }));
    await screen.findByRole("dialog");
    await user.keyboard("{Escape}");
    await waitFor(() => expect(document.activeElement).toBe(screen.getByRole("button", { name: "Create key" })));
    vi.unstubAllGlobals();
  });
});
