import { afterEach, describe, expect, it, vi } from "vitest";
import { api } from "../lib/api";
import { type Action } from "./ui";
import { PlatformAssignment, Catalogs, WorkspaceCatalogs, WorkspaceModelAccess, recipientGrantPath, catalogOverrideBody } from "../pages/model-access";
import { ScopeLimits } from "./scope-limits";
import { Models, Providers, Deployments } from "../pages/catalog";
import { Governance, Pricing, Routing, PriceVersions } from "../pages/governance";
import { PlatformTeams } from "../pages/hierarchy";
import { WorkspaceMembers, ServiceAccounts, Grants, addModelsAction } from "../pages/workspace";
import { Overview } from "../pages/overview";
import { contextOptions, scopeSearch } from "../lib/navigation";
import { canView, permissions } from "../lib/permissions";
import { jumpTargets } from "../lib/search";
import { policyFields, policyBody } from "../lib/governance";
import { admin, auditor, session, project, member, model, provider, policy, grant, markup, testClient } from "../lib/test-fixtures";
const captures = vi.hoisted(() => ({ ask: vi.fn(), clicks: new Map<string, () => void>() }));
vi.mock("./ui", async original => { const ui = await original<typeof import("./ui")>(); return { ...ui, useAction: () => captures.ask, Button: (props: React.ComponentProps<typeof ui.Button>) => { const label = Array.isArray(props.children) ? props.children.filter(c => typeof c === "string").join("") : String(props.children); if (props.onClick && !props.disabled) captures.clicks.set(label, props.onClick as () => void); return <ui.Button {...props} />; } }; });
vi.mock("../lib/api", async original => ({ ...await original<typeof import("../lib/api")>(), api: vi.fn().mockResolvedValue({ ok: true }) }));
function action(label: string): Action { const click = captures.clicks.get(label); expect(click).toBeDefined(); click!(); return captures.ask.mock.lastCall![0]; }
const catalogRow = (g: typeof grant) => ({ model_id: g.model_id, public_name: g.public_name, display_name: g.display_name, description: null, protocols: g.supported_protocols, workload: "generation", eligibility: "selected", reason: "Added to this workspace from an available catalog", min_input_microusd_per_million: null, min_output_microusd_per_million: null, routes: 1 });
function choices(path: string, data: unknown[]) { const client = testClient(); client.setQueryData(["api", undefined, path, "choices"], data); return client; }
const signal = new AbortController().signal;
afterEach(() => { captures.clicks.clear(); vi.clearAllMocks(); });
describe("installation infrastructure boundary", () => {
  it("keeps legacy route and routing pages reachable by deep link but out of jump search", () => { const empty = { ...admin, workspaces: [] }; for (const page of ["deployments", "routing"] as const) { expect(canView(page, empty)).toBe(true); expect(canView(page, session, project)).toBe(false); expect(jumpTargets(empty).find(t => t.id === `page:${page}`)).toBeUndefined(); } expect(jumpTargets(empty).find(t => t.id === "page:models")?.keywords).toContain("deployments"); });
  it.each(["models", "providers", "platform-audit", "catalogs", "platform-projects"] as const)("offers %s without memberships and clears stale workspace context", page => { const empty = { ...admin, workspaces: [] }; expect(canView(page, empty)).toBe(true); expect(scopeSearch(page, "private")).toEqual({ page, ws: undefined }); expect(jumpTargets(empty).find(t => t.id === `page:${page}`)).toBeDefined(); expect(canView(page, session, project)).toBe(false); });
  it("reads infrastructure only from platform paths", () => { expect(markup(<Models session={admin} />, [], choices("/api/v1/platform/models?sort=name", [model]))).toContain("Smart model"); expect(markup(<Providers session={admin} />, [["/api/v1/platform/providers?limit=50&offset=0", { data: [provider] }]])).toContain("Production provider"); expect(markup(<Deployments session={admin} />, [["/api/v1/platform/deployments?limit=50&offset=0", { data: [{ id: "d", upstream_model: "global-deployment", model_id: model.id, provider_connection_id: provider.id, enabled: true }] }]])).toContain("global-deployment"); });
  it("Pricing left the sidebar: /admin/pricing opens the Models table with Unpriced only, and jump search finds it", () => {
    const empty = { ...admin, workspaces: [] };
    expect(canView("pricing", empty)).toBe(true);
    expect(jumpTargets(empty).find(t => t.id === "page:pricing")).toBeUndefined();
    expect(jumpTargets(empty).find(t => t.id === "page:unpriced-models")?.search).toEqual({ page: "models", layout: "table", pricing: "unpriced" });
    expect(jumpTargets(empty).find(t => t.id === "page:models")?.keywords).toContain("pricing");
    expect(jumpTargets(auditor).find(t => t.id === "page:unpriced-models")).toBeDefined();
    expect(jumpTargets(session).find(t => t.id === "page:unpriced-models")).toBeUndefined();
    expect(markup(<Pricing session={admin} />)).toContain('href="/admin/models?layout=table&amp;pricing=unpriced"');
  });
  it("uses platform-wide routing choices", () => { const models = choices("/api/v1/platform/models", [model]); expect(markup(<Routing session={admin} />, [], models)).toContain(model.public_name); models.clear(); });
  it("offers the v3 price editor, and the OpenRouter import only for OpenRouter routes", () => { const path = "/api/v1/platform/deployments/d/prices", d = { id: "d", model_id: model.id, provider_connection_id: provider.id, upstream_model: "openai/gpt-x", enabled: true }, fixtures = (profile: string): [string, unknown][] => [[`/api/v1/platform/models/${model.id}`, model], [`/api/v1/platform/providers/${provider.id}`, { ...provider, provider: profile }], [`${path}?limit=1&offset=0`, { data: [] }]]; const openrouter = markup(<PriceVersions path={path} writable deployment={d} />, fixtures("openrouter")); expect(openrouter).toContain("Publish price version"); expect(openrouter).toContain("Import current OpenRouter price"); expect(captures.clicks.get("Publish price version")).toBeDefined(); expect(captures.ask).not.toHaveBeenCalled(); expect(markup(<PriceVersions path={path} writable deployment={d} />, fixtures("openai"))).not.toContain("Import current OpenRouter price"); expect(markup(<PriceVersions path={path} writable={false} deployment={d} />, fixtures("openrouter"))).not.toContain("Import current OpenRouter price"); });
  it("replaces obsolete organization assignments with approved catalog collections", () => { const html = markup(<Catalogs session={admin} />); expect(html).toContain("Catalogs"); expect(html).toContain(">Defaults<"); expect(html).toContain("A catalog is a set of approved models"); for (const old of ["Personal defaults", "Team defaults", "Project defaults"]) expect(html).not.toContain(old); expect(html).not.toContain("organization"); });
  it("selected workspace models contain no infrastructure writes", () => { const html = markup(<Grants session={session} workspace={member} />, [], choices("/api/v1/workspaces/team/catalog", [catalogRow(grant)])); expect(html).toContain("Smart model"); expect(html).not.toContain("Create alias"); expect(html).not.toContain("Disable</button>"); });
});
describe("independent model sources and live availability", () => {
  it("adds several available models at once with human protocol labels and per-item retry", async () => {
    const html = markup(<Grants session={session} workspace={member} />, [], choices("/api/v1/workspaces/team/catalog", [{ ...catalogRow(grant), protocols: ["audio_speech"], workload: "audio_speech" }]));
    expect(html).toContain("Text to speech"); expect(html).not.toContain("audio_speech");
    const choicesList = [{ ...grant, model_id: "m1", display_name: "One" }, { ...grant, model_id: "m2", display_name: "Two" }, { ...grant, model_id: "m3", display_name: "Three" }];
    const add = addModelsAction("/api/v1/workspaces/team/models", choicesList);
    expect(add.fields?.[0]).toMatchObject({ type: "checkboxes", maxSelections: 3 });
    vi.mocked(api).mockResolvedValueOnce({ ok: true }).mockRejectedValueOnce(new Error("Model is no longer available")).mockResolvedValueOnce({ ok: true });
    await expect(add.run({ model_ids: JSON.stringify(["m1", "m2", "m3"]) }, signal)).rejects.toThrow("Added 2 of 3 models. Not added: Two (Model is no longer available).");
    expect(vi.mocked(api).mock.calls.map(c => (c[1] as { body: { model_id: string } }).body.model_id)).toEqual(["m1", "m2", "m3"]);
    vi.mocked(api).mockClear();
    await add.run({ model_ids: JSON.stringify(["m1", "m2", "m3"]) }, signal);
    expect(vi.mocked(api).mock.calls.map(c => (c[1] as { body: { model_id: string } }).body.model_id)).toEqual(["m2"]);
  });
  it("does not offer catalog removal for direct-only models", () => { const client = choices("/api/v1/workspaces/project/catalog", [{ ...catalogRow(grant), eligibility: "direct", reason: "Assigned to this workspace by a Platform Admin" }]); client.setQueryData(["api", undefined, "/api/v1/workspaces/project/models", "choices"], [{ ...grant, catalog_granted: false, direct_granted: true, available_from_catalog: false }]); const html = markup(<Grants session={session} workspace={project} />, [], client); expect(html).toContain("Assigned by admin"); expect(html).toContain("Assigned to this workspace by a Platform Admin"); expect(html).not.toContain("Remove</button>"); client.clear(); });
  it("directly assigns several global aliases, excluding already assigned ones", async () => { const other = { ...model, id: "other", public_name: "company/other", display_name: "Other" }, client = choices("/api/v1/platform/models", [model, other]); client.setQueryData(["api", undefined, "/api/v1/workspaces/project/models", "choices"], [{ ...grant, model_id: model.id, catalog_granted: false, direct_granted: true, supported_protocols: ["chat_completions"] }]); const html = markup(<PlatformAssignment session={admin} workspace={project} />, [], client); expect(html).toContain("Direct"); expect(html).toContain("Remove</button>"); const assign = action("Assign models"); expect(assign.fields?.[0]).toMatchObject({ type: "checkboxes" }); expect(assign.fields?.[0].options?.map(o => o.value)).toEqual(["other"]); await assign.run({ model_ids: JSON.stringify(["other"]) }, signal); expect(api).toHaveBeenCalledWith("/api/v1/platform/workspaces/project/models", { method: "POST", body: { model_id: "other" }, signal }); client.clear(); });
  it("removes only the direct source, never a catalog source", async () => { const client = choices("/api/v1/platform/models", [model]); client.setQueryData(["api", undefined, "/api/v1/workspaces/project/models", "choices"], [{ ...grant, model_id: "both", catalog_granted: true, direct_granted: true }, { ...grant, model_id: "catalog", public_name: "company/catalog", catalog_granted: true, direct_granted: false }]); const html = markup(<PlatformAssignment session={admin} workspace={project} />, [], client); expect(html.match(/Remove<\/button>/g)).toHaveLength(1); expect(html).toContain("Catalog"); const remove = action("Remove"); expect(remove.description).toContain("stays available through"); await remove.run({}, signal); expect(api).toHaveBeenCalledWith("/api/v1/platform/workspaces/project/models/both", { method: "DELETE", signal }); client.clear(); });
  it("keeps direct and self-service source endpoints distinct", () => { expect(recipientGrantPath("project")).toBe("/api/v1/platform/workspaces/project/models"); expect(recipientGrantPath("personal")).toBe("/api/v1/platform/workspaces/personal/models"); expect(recipientGrantPath("project")).not.toBe("/api/v1/workspaces/project/models"); });
  it("uses replacement headers, including deliberate empty overrides", () => { expect(catalogOverrideBody({ catalog_ids: "[]" })).toEqual({ mode: "replace", catalog_ids: [] }); expect(catalogOverrideBody({ catalog_ids: '["one","two"]' })).toEqual({ mode: "replace", catalog_ids: ["one", "two"] }); });
  it("shows live defaults by name and an explicit none state, without a stray reset button", () => { const client = choices("/api/v1/platform/catalogs", [{ id: "one", name: "Approved" }, { id: "two", name: "Local" }]); const html = markup(<WorkspaceCatalogs session={admin} workspaceId="project" kind="project" />, [["/api/v1/platform/workspaces/project/catalogs", { mode: "replace", catalog_ids: [], effective_catalog_ids: [] }], ["/api/v1/platform/workspace-types/project/catalogs", { kind: "project", catalog_ids: ["one", "two"] }]], client); expect(html).toContain("Use Project defaults"); expect(html).toContain("Defaults: Approved · Local"); expect(html).toContain("Choose catalogs"); expect(html).toContain("No catalogs"); expect(html).toContain("own catalog choice"); expect(html).not.toContain("Reset to inheritance"); expect(html).not.toContain("Effective availability"); client.clear(); });
  it("combines catalogs and specific models in one Model access tab", () => { const client = choices("/api/v1/platform/catalogs", []); const html = markup(<WorkspaceModelAccess session={admin} workspace={project} />, [["/api/v1/platform/workspaces/project/catalogs", { mode: "inherit", catalog_ids: [], effective_catalog_ids: [] }]], client); expect(html).toContain("Catalogs"); expect(html).toContain("Specific models"); expect(html).toContain("Use Project defaults"); client.clear(); });
  it("Auditor has no assignment writes", () => { const html = markup(<PlatformAssignment session={auditor} workspace={project} />); expect(html).not.toContain("Assign models</button>"); });
});
describe("Project parity and composed limits", () => {
  it("groups project-only access without inferred Team membership", () => { const manager = { ...session, workspaces: [project] }; expect(contextOptions(manager).map(g => g.label)).toEqual(["Projects"]); expect(jumpTargets(manager, project).find(t => t.id === "workspace:project")?.group).toBe("Projects"); expect(permissions(manager, project)).toMatchObject({ manageTeam: true, manageServiceAccounts: true, managePolicy: true, manageGrants: true }); expect(permissions(manager, { ...member, kind: "project" })).toMatchObject({ managePolicy: false, manageTeam: false }); });
  it("creates Project siblings with explicit owner membership", async () => { const client = choices("/api/v1/platform/users?status=active", [{ id: "owner", email: "owner@example.invalid", platform_role: "user", disabled_at: null }, { id: "gone", email: "gone@example.invalid", platform_role: null, disabled_at: "2026-01-01T00:00:00Z" }]); markup(<PlatformTeams session={admin} kind="project" />, [], client); const create = action("Create project"); expect(create.fields?.find(f => f.name === "owner_user_id")?.options).toEqual([{ value: "owner", label: "owner@example.invalid" }]); client.clear(); await create.run({ name: "Research", owner_user_id: "owner" }, signal); expect(api).toHaveBeenCalledWith("/api/v1/platform/workspaces", { method: "POST", body: { name: "Research", kind: "project", owner_user_id: "owner" }, signal }); });
  it("uses Project context for overview, membership and service accounts", () => { expect(markup(<Overview session={session} workspace={project} />)).toContain("Project · showing everyone&#x27;s activity"); expect(markup(<WorkspaceMembers session={session} workspace={project} />)).toContain("Project members"); expect(markup(<ServiceAccounts session={session} workspace={project} />)).toContain("apps and automations"); });
  it("keeps editable local restrictions below inherited ceilings", () => { const ceiling = { ...policy, requests_per_minute: 120, monthly_budget_microusd: "50000000" }; expect(policyFields(policy, ceiling)[0].validate?.("121", {})).toContain("cannot exceed"); expect(policyFields(policy, ceiling)[3].validate?.("50.000001", {})).toContain("cannot exceed"); expect(policyBody({ requests_per_minute: "100", tokens_per_minute: "", concurrent_requests: "", monthly_budget_usd: "" })).toEqual({ ...policy, requests_per_minute: 100 }); });
  it("labels replacement override provenance and consumption honestly", () => { const typeDefault = { ...policy, requests_per_minute: 60, monthly_budget_microusd: "100000000", budget_period: "month" }; const html = markup(<ScopeLimits mode="replacement" kind="project" path="/api/v1/platform/workspaces/project/policy" writable />, [["/api/v1/platform/workspaces/project/policy", { policy: { ...policy, budget_period: "week" }, effective: policy, mode: "replace", provenance: { platform_source: "workspace_override", platform: policy, local: policy, key: null, type_default: typeDefault }, budgets: [{ layer: "platform", monthly_budget_microusd: "5000000", budget_period: "week", window_start: "2026-10-05T00:00:00Z", window_end: "2026-10-12T00:00:00Z", usage_visible: true, used_microusd: "1250000", unresolved_usage: false }] }]]); expect(html).toContain("Use Project defaults"); expect(html).toContain("Override for this project"); expect(html).toContain("Current Project defaults: 60 RPM"); expect(html).toContain("$100.00 monthly"); expect(html).toContain("No limit · default 60"); expect(html).toContain("Platform override weekly budget"); expect(html).toContain("Monthly budget"); expect(html).toContain("Budget used this period"); expect(html).toContain("$1.25"); expect(html).toContain("Platform override"); expect(html).not.toContain("Reset to inheritance"); });
  it("shows inherited placeholders for tighten-only workspace limits", () => { const platform = { ...policy, requests_per_minute: 60, monthly_budget_microusd: "100000000", budget_period: "month" }; const html = markup(<ScopeLimits mode="local" path="/api/v1/workspaces/project/policy" writable />, [["/api/v1/workspaces/project/policy", { policy, effective: platform, provenance: { platform_source: "type_default", platform, local: policy, key: null } }]]); expect(html).toContain('placeholder="Inherited: 60"'); expect(html).toContain("Add monthly cap"); expect(html).toContain("$100.00"); expect(html).not.toContain("Override for this"); });
  it("allows Project admins to tighten only their own scope, members read-only", () => { const path = "/api/v1/workspaces/project/policy", response = { policy, effective: policy, provenance: { platform_source: "type_default", platform: policy, local: policy, key: null } }; expect(markup(<Governance session={session} workspace={project} />, [[path, response]])).not.toContain("Only workspace admins change these limits."); expect(markup(<Governance session={session} workspace={{ ...member, id: "project", kind: "project" }} />, [[path, response]])).toContain("Only workspace admins change these limits."); });
});
