import { describe, expect, it } from "vitest";
import { authorityLabel, ownKeyHelp } from "../lib/access";
import { WorkspaceDetail, WorkspaceSettings } from "../pages/resource-details";
import { PlatformOverview } from "../pages/start";
import { Keys } from "../pages/workspace";
import { ResourcePage } from "./resource-page";
import { Heading } from "./ui";
import { admin, auditor, session, personal, team, project, member, none, markup, testClient } from "../lib/test-fixtures";
const tabs = (html: string) => [...html.matchAll(/role="tab"[^>]*>((?:(?!<\/button>).)*)<\/button>/g)].map(m => m[1]!.replace(/<[^>]+>/g, "").trim());
const noop = () => {};
describe("Grounded resource composition", () => {
  it("renders only the active panel and nests section headings", () => { const html = markup(<ResourcePage title="Resource" tab="second" onTabChange={noop} tabs={[{ value: "first", label: "First", content: <Heading title="Inactive private section" /> }, { value: "second", label: "Second", content: <Heading title="Active section" /> }]} />); expect(html.match(/<h1\b/g)).toHaveLength(1); expect(html).toMatch(/<h2[^>]*>Active section/); expect(html).not.toContain("Inactive private section"); expect(html).toContain('aria-label="Resource sections"'); });
  it("falls back to an available tab without forbidden content", () => { const html = markup(<ResourcePage title="Resource" tab="forbidden" onTabChange={noop} tabs={[{ value: "overview", label: "Overview", content: "Safe overview" }]} />); expect(html).toContain("Safe overview"); expect(html).not.toContain('value="forbidden"'); });
  it("loads administrative shared resources by exact ID and rejects personal/mismatched detail", () => { const path = "/api/v1/platform/workspaces/team"; const html = markup(<WorkspaceDetail session={admin} id="team" onTabChange={noop} />, [[path, team]]); expect(html).toContain("Product"); expect(html).toContain("Your membership"); expect(html).not.toContain("Personal"); expect(markup(<WorkspaceDetail session={admin} id="team" onTabChange={noop} />, [[path, personal]])).toContain("does not match"); });
  it("personal ownership never grants Platform administration", () => expect(markup(<PlatformOverview session={session} />)).toContain("Access not available"));
  it("never offers members/service accounts/invitations or rename for personal workspaces", () => { const html = markup(<WorkspaceSettings session={session} workspace={personal} onTabChange={noop} />); expect(tabs(html)).toEqual(["Limits", "Audit log"]); expect(html).not.toContain('name="name"'); expect(html).toContain("Platform admins can see its cost totals"); expect(html).toContain("Loading limits"); });
  it("keeps API keys and Usage & costs out of settings", () => { const html = markup(<WorkspaceSettings session={session} workspace={team} tab="keys" onTabChange={noop} />); expect(tabs(html)).toEqual(["General", "Members", "Service accounts", "Limits", "Audit log"]); expect(html).not.toContain("One-time token"); });
  it("preserves member limits reads without management panels", () => { const html = markup(<WorkspaceSettings session={session} workspace={member} tab="limits" onTabChange={noop} />); expect(tabs(html)).toEqual(["General", "Members", "Limits", "Audit log"]); expect(html).toContain("Loading limits"); expect(html).not.toContain('>Service accounts</'); expect(html).not.toContain("Save limits"); });
  it("does not issue a human credential to a nonmember staff admin", () => { const ws = { ...team, role: null, membership_source: null, capabilities: { ...none, manage_service_accounts: true, manage_members: true } }, client = testClient(); client.setQueryData(["api", undefined, "/api/v1/workspaces/team/models", "choices"], []); client.setQueryData(["api", undefined, "/api/v1/workspaces/team/service-accounts", "choices"], []); const html = markup(<Keys session={admin} workspace={ws} />, [], client); expect(html.match(/<button[^>]*>Create key<\/button>/)?.[0]).toContain("disabled"); expect(html).toContain("only create keys for service accounts"); expect(ownKeyHelp(ws)).toContain("aren't a member"); client.clear(); });
  it("does not fabricate setup success or upstream readiness while loading", () => { const html = markup(<PlatformOverview session={admin} />); expect(html).toContain("Loading platform overview"); expect(html).not.toMatch(/of \d+ done/); expect(html).not.toContain("Ready models"); });
  it("Auditor cannot write shared administrative settings", () => { const html = markup(<WorkspaceDetail session={auditor} id="team" tab="settings" onTabChange={noop} />, [["/api/v1/platform/workspaces/team", team]]); expect(html).not.toContain("cannot change"); expect(html).not.toContain("<select"); expect(html).not.toContain("Save settings"); expect(html).not.toContain("Disable workspace</button>"); });
});
describe("authority provenance labels", () => {
  it("labels kind and role only, never provenance or staff access", () => { expect(authorityLabel({ ...team, role: null, membership_source: null })).toBe("Team"); expect(authorityLabel({ ...team, membership_source: "mixed" })).toBe("Team · Admin"); expect(authorityLabel({ ...project, role: "member" })).toBe("Project · Member"); expect(authorityLabel(personal)).toBe("Private"); for (const ws of [team, project, personal]) expect(authorityLabel(ws)).not.toMatch(/staff|membership|mixed|group/i); });
});
