// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { render, screen, waitFor, cleanup, act } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClientProvider } from "@tanstack/react-query";
import { createMemoryHistory, createRouter, RouterProvider } from "@tanstack/react-router";
import { dashboardRouteTree } from "../router";
import { admin, auditor, report, grant, model, testClient } from "../lib/test-fixtures";
import { abortRequests } from "../lib/api";
beforeEach(() => { document.cookie = "omg_csrf=test-csrf; Path=/"; localStorage.clear(); sessionStorage.clear(); Object.defineProperty(Element.prototype, "getAnimations", { configurable: true, value: () => [] }); vi.stubGlobal("ResizeObserver", class { observe() {} unobserve() {} disconnect() {} }); Object.defineProperty(window, "matchMedia", { configurable: true, value: () => ({ matches: false, addListener() {}, removeListener() {}, addEventListener() {}, removeEventListener() {}, dispatchEvent() { return false; } }) }); });
afterEach(() => { cleanup(); abortRequests(); vi.unstubAllGlobals(); vi.restoreAllMocks(); });
async function mount(href: string, client = testClient()) { const router = createRouter({ routeTree: dashboardRouteTree, history: createMemoryHistory({ initialEntries: [href] }) }); await router.load(); const ui = render(<QueryClientProvider client={client}><RouterProvider router={router} /></QueryClientProvider>); return { router, client, ...ui }; }
describe("actual session/shell transport boundaries", () => {
  it("clears private cached rows, dialogs and transient tokens on protected 401", async () => { const user = userEvent.setup(), key = { id: "key", name: "Private credential metadata", issued_to_user_id: "me", service_account_id: null, expires_at: "2099-01-01T00:00:00Z", revoked_at: null, created_at: "2026-01-01T00:00:00Z" }, fetch = vi.fn().mockImplementation((path: string, options?: RequestInit) => { if (path === "/api/v1/me") return Promise.resolve(Response.json(admin)); if (options?.method === "POST" && path.endsWith("/keys")) return Promise.resolve(Response.json({ id: "new", token: "transient-token" })); if (path.includes("/keys?")) return Promise.resolve(Response.json({ data: [key], has_more: false })); if (path.includes("/models?")) return Promise.resolve(Response.json({ data: [grant], has_more: false })); return Promise.resolve(Response.json({ data: [], has_more: false })); }); vi.stubGlobal("fetch", fetch); const result = await mount("/workspaces/team/keys"); await screen.findByText("Private credential metadata"); await waitFor(() => expect((screen.getByRole("button", { name: "Create key" }) as HTMLButtonElement).disabled).toBe(false)); await user.click(screen.getByRole("button", { name: "Create key" })); await user.type(screen.getByRole("textbox", { name: /^Name/ }), "Browser test"); await user.click(screen.getByRole("button", { name: "Create key" })); await screen.findByRole("textbox", { name: "API key" }); await act(async () => { window.dispatchEvent(new Event("omg:unauthorized")); }); await screen.findByRole("link", { name: "Sign in with single sign-on" }); expect(screen.queryByRole("dialog")).toBeNull(); const cached = JSON.stringify(result.client.getQueryCache().getAll().map(q => ({ key: q.queryKey, data: q.state.data }))); expect(cached).not.toContain("Private credential metadata"); expect(cached).not.toContain("transient-token"); expect(result.client.getMutationCache().getAll()).toEqual([]); expect(document.body.textContent).not.toContain("transient-token"); result.client.clear(); });
  it("reauthorizes fresh Auditor inventory and removes writes/stale private scopes", async () => { const user = userEvent.setup(), client = testClient(); let current = admin; client.setQueryData(["api", JSON.stringify(admin), "/api/v1/workspaces/team/keys"], { data: [{ name: "stale-shared-private-record" }] }); const fetch = vi.fn().mockImplementation((path: string) => { if (path === "/api/v1/me") return Promise.resolve(Response.json(current)); if (path.startsWith("/api/v1/platform/models")) return Promise.resolve(Response.json({ data: [model], has_more: false })); if (path.includes("cost-report")) return Promise.resolve(Response.json(report)); return Promise.resolve(Response.json({ data: [], has_more: false })); }); vi.stubGlobal("fetch", fetch); const result = await mount("/admin/models", client); await screen.findByRole("link", { name: "Add model" }); current = auditor; await act(async () => { window.dispatchEvent(new Event("omg:access-refresh")); }); await screen.findByText("Read-only"); expect(screen.queryByRole("link", { name: "Add model" })).toBeNull(); expect(JSON.stringify(client.getQueryCache().getAll().map(q => q.state.data))).not.toContain("stale-shared-private-record"); await user.click(screen.getByRole("link", { name: "Workspace" })); await waitFor(() => expect(result.router.state.location.pathname).toBe("/home")); expect(fetch.mock.calls.some(call => /^\/api\/v1\/workspaces\/team\/(keys|executions|cost-report)/.test(String(call[0])))).toBe(false); client.clear(); });
});
