// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { render, screen, waitFor, cleanup, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClientProvider } from "@tanstack/react-query";
import { createMemoryHistory, createRouter, RouterProvider } from "@tanstack/react-router";
import { dashboardRouteTree } from "../router";
import { abortRequests, type Session } from "../lib/api";
import { ActionProvider } from "./ui";
import { WorkspaceMembers } from "../pages/workspace";
import { admin, auditor, grant, member, personal, policy, project, session, team, testClient } from "../lib/test-fixtures";
beforeEach(() => { document.cookie = "omg_csrf=test-csrf; Path=/"; localStorage.clear(); sessionStorage.clear(); Object.defineProperty(Element.prototype, "getAnimations", { configurable: true, value: () => [] }); vi.stubGlobal("ResizeObserver", class { observe() {} unobserve() {} disconnect() {} }); Object.defineProperty(window, "matchMedia", { configurable: true, value: () => ({ matches: false, addListener() {}, removeListener() {}, addEventListener() {}, removeEventListener() {}, dispatchEvent() { return false; } }) }); });
afterEach(() => { cleanup(); abortRequests(); vi.unstubAllGlobals(); vi.restoreAllMocks(); });
const usage = (cost: string, requests: string, tokens: string) => ({ known_cost_microusd: cost, held_microusd: "0", requests, attempts: requests, unresolved_attempts: "0", input_tokens: tokens, output_tokens: "0", tokens, unknown_token_attempts: "0" });
const summary = { currency: "USD", basis: "configured_rate_estimate", observed_at: "2026-10-08T00:00:00Z", period: { current: { start_date: "2026-10-01", end_date: "2026-11-01" }, previous: { start_date: "2026-09-01", end_date: "2026-10-01" } }, totals: { current: usage("2700", "21", "1500"), previous: usage("1350", "21", "3000") }, workspaces: [{ workspace_id: "personal", name: "Personal", kind: "personal", role: "owner", current: usage("0", "0", "0"), previous: null }, { workspace_id: "team", name: "Product", kind: "team", role: "admin", current: usage("2700", "21", "1500"), previous: null }] };
const myKey = { id: "k1", name: "My laptop key", workspace: { id: "team", name: "Product", kind: "team" }, status: "active", created_at: "2026-10-01T00:00:00Z", expires_at: "2099-01-01T00:00:00Z", revoked_at: null, disabled_at: null, last_used_at: null, model_ids: null, usage: { period: "month", used_microusd: "1240000", limit_microusd: "5000000", window_start: "2026-10-01T00:00:00Z", window_end: "2026-11-01T00:00:00Z", unresolved_usage: false } };
type Handler = (path: string, init?: RequestInit) => unknown;
function serve(actor: Session, extra: Handler = () => undefined) {
  const fetch = vi.fn().mockImplementation((path: string, init?: RequestInit) => { const custom = extra(path, init); if (custom instanceof Response) return Promise.resolve(custom); if (custom !== undefined) return Promise.resolve(Response.json(custom)); if (path === "/api/v1/me") return Promise.resolve(Response.json(actor)); return Promise.resolve(Response.json({ data: [], has_more: false })); });
  vi.stubGlobal("fetch", fetch); return fetch;
}
async function mount(href: string, client = testClient()) { const router = createRouter({ routeTree: dashboardRouteTree, history: createMemoryHistory({ initialEntries: [href] }) }); await router.load(); const ui = render(<QueryClientProvider client={client}><RouterProvider router={router} /></QueryClientProvider>); return { router, client, ...ui }; }
const sectionLabels = () => [...document.querySelectorAll('nav[aria-label="Main"] ul[aria-labelledby]')].map(e => document.getElementById(e.getAttribute("aria-labelledby")!)?.textContent?.trim());
const switcher = () => [...document.querySelectorAll("button")].find(b => b.textContent?.includes("Current workspace:"))!;
const sidebarLinks = () => [...document.querySelectorAll('nav[aria-label="Main"] a')].map(a => [a.textContent?.trim(), a.getAttribute("href")]);
describe("Workspace portal shell", () => {
  it("lands on Home with Personal selected after sign-in, even if another workspace was selected before", async () => { serve(session); sessionStorage.setItem("omg:enterprise:portal:me:context", "team"); const { router, client } = await mount("/"); await waitFor(() => expect(router.state.location.pathname).toBe("/home")); await screen.findByRole("heading", { name: "Welcome" }); expect(sessionStorage.getItem("omg:enterprise:portal:me:context")).toBe("personal"); expect(sectionLabels()).toEqual(["Workspace", "Personal"]); expect(sidebarLinks()).toEqual([["Home", "/home"], ["Overview", "/workspaces/personal"], ["Models", "/workspaces/personal/models"], ["API keys", "/workspaces/personal/keys"], ["Logs", "/workspaces/personal/logs"], ["Usage & costs", "/workspaces/personal/costs"], ["Settings", "/workspaces/personal/settings"]]); expect(switcher().textContent).toContain("Current workspace: PersonalPrivate"); client.clear(); });
  it("titles the lower sidebar group with the selected workspace and keeps it on Home", async () => { serve(session); const { router, client } = await mount("/workspaces/project/keys"); await screen.findByRole("heading", { name: "API keys" }); expect(sectionLabels()).toEqual(["Workspace", "Research"]); expect(document.querySelector('nav[aria-label="Main"] a[aria-current="page"]')?.getAttribute("href")).toBe("/workspaces/project/keys"); const crumbs = screen.getByRole("navigation", { name: /breadcrumb/i }); expect(within(crumbs).getByText("Research")).toBeTruthy(); await userEvent.setup().click(screen.getAllByRole("link", { name: "Home" })[0]!); await waitFor(() => expect(router.state.location.pathname).toBe("/home")); expect(sectionLabels()).toEqual(["Workspace", "Research"]); client.clear(); });
  it("keeps Admin navigation unchanged for platform staff", async () => { serve(admin); const { client } = await mount("/admin/users"); await screen.findByRole("heading", { name: "Users" }); expect(sectionLabels()).toEqual(["People", "Models", "Usage & spend", "Records", "Settings"]); client.clear(); });
  it("shows Platform Admins only their real memberships and sends non-member workspace URLs Home", async () => { const research = { ...project, role: null, membership_source: null }; const actor: Session = { ...admin, workspaces: [personal, team, research] }; const fetch = serve(actor); const { router, client } = await mount("/workspaces/project"); await waitFor(() => expect(router.state.location.pathname).toBe("/home")); await screen.findByRole("heading", { name: "Welcome" }); await userEvent.setup().click(switcher()); const menu = await screen.findByRole("menu"); expect(within(menu).queryByText("Research")).toBeNull(); expect(within(menu).getByText("Team · Admin")).toBeTruthy(); expect(document.body.textContent).not.toMatch(/Platform staff|No membership/); expect(fetch.mock.calls.some(c => String(c[0]).startsWith("/api/v1/workspaces/project"))).toBe(false); client.clear(); });
});
describe("Home", () => {
  it("shows only the caller's own usage, keys and memberships", async () => { const fetch = serve(session, path => path === "/api/v1/me/summary" ? summary : path.startsWith("/api/v1/me/keys") ? { data: [myKey], has_more: false } : path.startsWith("/api/v1/workspaces/team/catalog") ? { data: [{ model_id: grant.model_id, public_name: grant.public_name, display_name: grant.display_name, eligibility: "selected", routes: 1 }], has_more: false } : undefined); const { client } = await mount("/home"); await screen.findByText("My laptop key"); expect(screen.getAllByText("$0.0027").length).toBeGreaterThan(0); expect(screen.getByText("+100%")).toBeTruthy(); expect(screen.getByText("$1.24 / $5.00 · Monthly")).toBeTruthy(); expect(await screen.findByText("Smart model")).toBeTruthy(); const teams = screen.getByRole("list", { name: "Your teams & projects" }); expect(within(teams).getByRole("link", { name: "Product" })).toBeTruthy(); expect(within(teams).getByRole("link", { name: "Research: usage" }).getAttribute("href")).toBe("/workspaces/project/costs"); expect(screen.queryByText("Personal usage")).toBeNull(); expect(screen.queryByText("Personal models")).toBeNull(); expect(screen.getByRole("link", { name: /^All models in / }).getAttribute("href")).toMatch(/\/workspaces\/[^/]+\/models$/); const paths = fetch.mock.calls.map(c => String(c[0])); expect(paths.filter(p => /\/(keys|executions|cost-report|members|requests|usage)\b/.test(p) && !p.startsWith("/api/v1/me/"))).toEqual([]); expect(paths.some(p => p.startsWith("/api/v1/platform"))).toBe(false); client.clear(); });
  it("feature-detects missing /me endpoints and explains how to join a team", async () => { serve({ ...auditor, workspaces: [personal] }, path => path.startsWith("/api/v1/me/") ? new Response(JSON.stringify({ error: { code: "404", message: "Not found" } }), { status: 404, headers: { "content-type": "application/json" } }) : undefined); const { client } = await mount("/home"); await screen.findByText("You're not in a team or project yet."); await waitFor(() => expect(screen.getAllByText("Not available yet.")).toHaveLength(2)); expect(screen.getByText(/Platform Admins create them/)).toBeTruthy(); expect(screen.getByText(/read-only Admin/)).toBeTruthy(); client.clear(); });
});
describe("Settings", () => {
  it("shows Personal limits read-only, with no rename and a link to key caps", async () => { serve(session, path => path === "/api/v1/workspaces/personal/policy" ? { policy, effective: { ...policy, requests_per_minute: 60 }, provenance: { platform_source: "type_default", platform: { ...policy, requests_per_minute: 60 }, local: policy, key: null } } : undefined); const { client } = await mount("/workspaces/personal/settings"); await screen.findByText("Set by your platform. Contact a Platform Admin to change them."); expect(screen.getAllByRole("tab").map(t => t.textContent)).toEqual(["Limits", "Audit log"]); expect(screen.getByText("60 per minute")).toBeTruthy(); expect(document.querySelector("main input")).toBeNull(); expect(within(screen.getByRole("main")).getByRole("link", { name: "API keys" }).getAttribute("href")).toBe("/workspaces/personal/keys"); client.clear(); });
  it("adds a member by choosing a person, never by typing an ID", async () => { const user = userEvent.setup(); const fetch = serve(session, (path, init) => path.startsWith("/api/v1/workspaces/team/member-candidates?q=al") ? { data: [{ user_id: "u-alex", email: "alex@demo.invalid" }] } : init?.method === "POST" ? { ok: true } : undefined); const client = testClient(); render(<QueryClientProvider client={client}><ActionProvider><WorkspaceMembers session={session} workspace={team} /></ActionProvider></QueryClientProvider>); await user.click(screen.getByRole("button", { name: "Add member" })); const dialog = await screen.findByRole("dialog"); expect(within(dialog).queryByText(/user ID/i)).toBeNull(); await user.type(within(dialog).getByRole("combobox", { name: "Person" }), "al"); await user.click(await screen.findByRole("option", { name: "alex@demo.invalid" })); await user.click(within(dialog).getByRole("button", { name: "Add member" })); await waitFor(() => expect(fetch.mock.calls.some(c => c[1]?.method === "POST")).toBe(true)); const post = fetch.mock.calls.find(c => c[1]?.method === "POST")!; expect(post[0]).toBe("/api/v1/workspaces/team/members"); expect(JSON.parse(String(post[1].body))).toEqual({ user_id: "u-alex", role: "member" }); client.clear(); });
  it("falls back to email invitations when people search is unavailable", async () => { const user = userEvent.setup(); serve(session, path => path.includes("member-candidates") ? new Response(JSON.stringify({ error: { code: "404", message: "Not found" } }), { status: 404, headers: { "content-type": "application/json" } }) : undefined); const client = testClient(); render(<QueryClientProvider client={client}><ActionProvider><WorkspaceMembers session={session} workspace={team} /></ActionProvider></QueryClientProvider>); expect(screen.getByRole("button", { name: "Invite by email" })).toBeTruthy(); await user.click(screen.getByRole("button", { name: "Add member" })); await user.type(await screen.findByRole("combobox", { name: "Person" }), "x"); await screen.findByText("People search isn't available yet"); client.clear(); });
  it("shows members a read-only Members tab without fetching the member list", async () => { const fetch = serve({ ...session, workspaces: [personal, member] }); const { client } = await mount("/workspaces/team/settings?tab=members"); await screen.findByText(/Only workspace admins can see the full member list/); expect(screen.getAllByRole("tab").map(t => t.textContent)).toEqual(["General", "Members", "Limits", "Audit log"]); expect(screen.queryByRole("button", { name: "Add member" })).toBeNull(); expect(fetch.mock.calls.some(c => String(c[0]).includes("/members"))).toBe(false); client.clear(); });
});
