//! Encrypted object storage for gateway-owned files (docs/file-storage.md).
//!
//! Every backend stores ciphertext only: [`crypto`] wraps each object in
//! streaming, chunked AES-256-GCM before a backend sees a byte, and verifies
//! every chunk (plus truncation and reordering) on the way out. Backends:
//!
//! - `local`: one directory on the gateway host (0700 directories, 0600 files,
//!   temp file + fsync + atomic rename, no symlink following).
//! - `s3`: S3 and S3-compatible stores (AWS S3, MinIO, RustFS, Cloudflare R2,
//!   Wasabi, Ceph RGW, GCS interoperability) through `aws-sdk-s3`.
//! - memory: tests only ([`memory_store`]).
//!
//! Object keys are generated by the gateway (`<purpose>/<workspace-id|installation>/<uuid>`)
//! and never derived from client input. Metadata (owner, purpose, size, sha256,
//! retention) lives in PostgreSQL (`stored_files`, migration 0019) and is managed by
//! [`files::FileStorage`]; the raw [`FileStore`] trait does not touch the database.
use std::{fmt, sync::Arc, time::Duration};

use bytes::Bytes;
use uuid::Uuid;

pub mod config;
pub mod crypto;
pub mod files;
#[cfg(unix)]
mod local;
#[cfg(any(test, feature = "integration-tests"))]
mod memory;
pub mod multipart;
pub mod s3;
pub mod sweep;
pub mod upload;
pub mod usage;

pub use config::{BackendKind, FileStoreConfig, FileStoreRuntime};
pub use crypto::KeyRing;
pub use files::{FileError, FileStorage, NewFile, QuotaMode, StoredFile};
#[cfg(any(test, feature = "integration-tests"))]
pub use memory::memory_store;

/// A stream of plaintext (from [`FileStore::get`]) or caller-provided bytes (to [`FileStore::put`]).
pub type ByteStream = futures::stream::BoxStream<'static, Result<Bytes, FileStoreError>>;

/// Encrypted object storage. Implementations encrypt on `put` and authenticate
/// on `get`; a backend never receives plaintext.
#[async_trait::async_trait]
pub trait FileStore: Send + Sync {
    /// Streams `body` into the store under `key`. Returns the plaintext size
    /// and SHA-256. On any error nothing is left behind (temp files removed,
    /// multipart uploads aborted). A body error is returned unchanged.
    async fn put(
        &self,
        key: &ObjectKey,
        body: ByteStream,
        meta: PutMeta,
    ) -> Result<StoredObject, FileStoreError>;
    /// Decrypted plaintext stream. Every 64 KiB chunk is authenticated before it
    /// is yielded; truncation, reordering or tampering ends the stream with
    /// [`FileStoreError::Integrity`]. Treat any error item as failure of the whole object.
    async fn get(&self, key: &ObjectKey) -> Result<ByteStream, FileStoreError>;
    /// Idempotent: deleting a missing object succeeds.
    async fn delete(&self, key: &ObjectKey) -> Result<(), FileStoreError>;
    /// Size information without reading the object; `None` when absent.
    async fn head(&self, key: &ObjectKey) -> Result<Option<ObjectInfo>, FileStoreError>;
    /// Put/get/delete probe of a small random object under the configured prefix.
    async fn health(&self) -> Result<StoreHealth, FileStoreError>;
}

/// Options for one [`FileStore::put`].
#[derive(Clone, Copy, Debug, Default)]
pub struct PutMeta {
    /// Reject the upload with [`FileStoreError::TooLarge`] once the plaintext exceeds this.
    pub max_bytes: Option<u64>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StoredObject {
    pub key: ObjectKey,
    /// Plaintext bytes.
    pub size: u64,
    /// SHA-256 of the plaintext.
    pub sha256: [u8; 32],
    /// Master key id that wrapped this object's data key.
    pub key_id: String,
    /// Ciphertext bytes held by the backend (header + per-chunk tags).
    pub stored_size: u64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ObjectInfo {
    /// Plaintext bytes, derived from the ciphertext length.
    pub size: u64,
    pub stored_size: u64,
}

#[derive(Clone, Debug)]
pub struct StoreHealth {
    pub backend: BackendKind,
    /// Active encryption key id.
    pub key_id: String,
    pub round_trip: Duration,
}

/// Safe, fixed error categories. Never carries paths, keys, bucket names,
/// upstream messages or content.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FileStoreError {
    NotFound,
    TooLarge,
    /// Authentication failed: tampered, truncated, reordered or malformed ciphertext.
    Integrity,
    /// The object was encrypted under a key id that is not configured.
    KeyUnavailable,
    InvalidKey,
    /// The caller's body stream failed.
    Source,
    Unavailable,
    Timeout,
    /// The backend refused the credentials or permission.
    Denied,
    /// Local backend: a symlink or path outside the store directory.
    UnsafePath,
    /// No file store is configured, or the purpose is turned off.
    Disabled,
}

impl FileStoreError {
    /// Stable snake_case code for metrics, the database and API responses.
    pub fn code(self) -> &'static str {
        match self {
            Self::NotFound => "not_found",
            Self::TooLarge => "too_large",
            Self::Integrity => "integrity",
            Self::KeyUnavailable => "key_unavailable",
            Self::InvalidKey => "invalid_key",
            Self::Source => "source",
            Self::Unavailable => "unavailable",
            Self::Timeout => "timeout",
            Self::Denied => "denied",
            Self::UnsafePath => "unsafe_path",
            Self::Disabled => "disabled",
        }
    }
}

impl fmt::Display for FileStoreError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::NotFound => "stored object not found",
            Self::TooLarge => "stored object too large",
            Self::Integrity => "stored object failed integrity verification",
            Self::KeyUnavailable => "stored object encryption key is not configured",
            Self::InvalidKey => "invalid object key",
            Self::Source => "upload source failed",
            Self::Unavailable => "file store unavailable",
            Self::Timeout => "file store timed out",
            Self::Denied => "file store denied access",
            Self::UnsafePath => "unsafe file store path",
            Self::Disabled => "file storage is not enabled",
        })
    }
}

impl std::error::Error for FileStoreError {}

/// What a stored object is for. Stored in `stored_files.purpose`; extend with a
/// migration that widens its CHECK constraint.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Purpose {
    BatchInput,
    BatchOutput,
    Export,
    Branding,
    VideoOutput,
    /// Gateway-owned Files API uploads (OpenAI `user_data`, `vision`, …).
    UserFile,
}

/// Installation settings are per group: both batch purposes share one toggle and retention.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PurposeGroup {
    Batch,
    Video,
    UserFiles,
    Export,
    Branding,
}

impl Purpose {
    pub const ALL: [Purpose; 6] = [
        Self::BatchInput,
        Self::BatchOutput,
        Self::Export,
        Self::Branding,
        Self::VideoOutput,
        Self::UserFile,
    ];
    pub fn as_str(self) -> &'static str {
        match self {
            Self::BatchInput => "batch_input",
            Self::BatchOutput => "batch_output",
            Self::Export => "export",
            Self::Branding => "branding",
            Self::VideoOutput => "video_output",
            Self::UserFile => "user_file",
        }
    }
    pub fn parse(value: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|p| p.as_str() == value)
    }
    /// OpenAI Files API `purpose` values the gateway can hold. `fine-tune` and
    /// unknown values are not supported.
    pub fn from_openai(value: &str) -> Option<Self> {
        match value {
            "batch" => Some(Self::BatchInput),
            "user_data" | "assistants" | "vision" | "evals" => Some(Self::UserFile),
            _ => None,
        }
    }
    pub fn group(self) -> PurposeGroup {
        match self {
            Self::BatchInput | Self::BatchOutput => PurposeGroup::Batch,
            Self::VideoOutput => PurposeGroup::Video,
            Self::UserFile => PurposeGroup::UserFiles,
            Self::Export => PurposeGroup::Export,
            Self::Branding => PurposeGroup::Branding,
        }
    }
    /// Purposes that hold customer prompts/results need their own admin toggle.
    pub fn holds_customer_content(self) -> bool {
        self.group().holds_customer_content()
    }
    /// Branding is installation-wide; exports may be either; everything else
    /// belongs to one workspace.
    pub fn allows(self, scope: Scope) -> bool {
        match (self, scope) {
            (Self::Branding, Scope::Installation) => true,
            (Self::Branding, Scope::Workspace(_)) => false,
            (Self::Export, _) => true,
            (_, Scope::Workspace(_)) => true,
            (_, Scope::Installation) => false,
        }
    }
}

impl PurposeGroup {
    pub const ALL: [PurposeGroup; 5] = [
        Self::Batch,
        Self::Video,
        Self::UserFiles,
        Self::Export,
        Self::Branding,
    ];
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Batch => "batch",
            Self::Video => "video",
            Self::UserFiles => "user_files",
            Self::Export => "export",
            Self::Branding => "branding",
        }
    }
    pub fn holds_customer_content(self) -> bool {
        matches!(self, Self::Batch | Self::Video | Self::UserFiles)
    }
    pub fn purposes(self) -> &'static [Purpose] {
        match self {
            Self::Batch => &[Purpose::BatchInput, Purpose::BatchOutput],
            Self::Video => &[Purpose::VideoOutput],
            Self::UserFiles => &[Purpose::UserFile],
            Self::Export => &[Purpose::Export],
            Self::Branding => &[Purpose::Branding],
        }
    }
    /// Default retention in days; `None` means no expiry (branding).
    pub fn default_retention_days(self) -> Option<i32> {
        match self {
            Self::Batch | Self::Video => Some(7),
            Self::UserFiles => Some(30),
            Self::Export => Some(1),
            Self::Branding => None,
        }
    }
}

/// Who an object belongs to.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Scope {
    Workspace(Uuid),
    Installation,
}

impl Scope {
    pub fn workspace_id(self) -> Option<Uuid> {
        match self {
            Self::Workspace(id) => Some(id),
            Self::Installation => None,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
enum Prefix {
    File(Purpose),
    /// Health probes (`health/installation/<uuid>`); never recorded as files.
    Health,
}

/// A gateway-generated object key: `<purpose>/<workspace-uuid|installation>/<uuid>`.
/// Only lowercase ASCII letters, digits, `_`, `-` and two `/` separators, so it is
/// safe as a path below the local root and as an S3 key below the prefix.
#[derive(Clone, PartialEq, Eq, Hash)]
pub struct ObjectKey {
    prefix: Prefix,
    scope: Scope,
    id: Uuid,
    text: String,
}

impl fmt::Debug for ObjectKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "ObjectKey({})", self.text)
    }
}

impl fmt::Display for ObjectKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.text)
    }
}

impl ObjectKey {
    /// A fresh random key for `purpose` in `scope`.
    pub fn new(purpose: Purpose, scope: Scope) -> Result<Self, FileStoreError> {
        Self::with_id(purpose, scope, Uuid::new_v4())
    }

    pub(crate) fn with_id(
        purpose: Purpose,
        scope: Scope,
        id: Uuid,
    ) -> Result<Self, FileStoreError> {
        if !purpose.allows(scope) {
            return Err(FileStoreError::InvalidKey);
        }
        Ok(Self::build(Prefix::File(purpose), scope, id))
    }

    pub(crate) fn health_probe() -> Self {
        Self::build(Prefix::Health, Scope::Installation, Uuid::new_v4())
    }

    fn build(prefix: Prefix, scope: Scope, id: Uuid) -> Self {
        let head = match prefix {
            Prefix::File(p) => p.as_str(),
            Prefix::Health => "health",
        };
        let scope_text = match scope {
            Scope::Workspace(ws) => ws.hyphenated().to_string(),
            Scope::Installation => "installation".to_owned(),
        };
        let text = format!("{head}/{scope_text}/{}", id.hyphenated());
        Self {
            prefix,
            scope,
            id,
            text,
        }
    }

    /// Strictly parses a key previously generated by the gateway (for example
    /// from `stored_files.object_key`). Only the canonical form is accepted.
    pub fn parse(value: &str) -> Result<Self, FileStoreError> {
        let mut parts = value.split('/');
        let (Some(purpose), Some(scope), Some(id), None) =
            (parts.next(), parts.next(), parts.next(), parts.next())
        else {
            return Err(FileStoreError::InvalidKey);
        };
        let purpose = Purpose::parse(purpose).ok_or(FileStoreError::InvalidKey)?;
        let scope = if scope == "installation" {
            Scope::Installation
        } else {
            Scope::Workspace(canonical_uuid(scope)?)
        };
        let key = Self::with_id(purpose, scope, canonical_uuid(id)?)?;
        if key.text != value {
            return Err(FileStoreError::InvalidKey);
        }
        Ok(key)
    }

    pub fn purpose(&self) -> Option<Purpose> {
        match self.prefix {
            Prefix::File(p) => Some(p),
            Prefix::Health => None,
        }
    }
    pub fn scope(&self) -> Scope {
        self.scope
    }
    pub fn id(&self) -> Uuid {
        self.id
    }
    pub fn as_str(&self) -> &str {
        &self.text
    }
    /// The three path components, each from the safe charset.
    pub(crate) fn components(&self) -> [&str; 3] {
        let mut it = self.text.splitn(3, '/');
        [
            it.next().unwrap_or_default(),
            it.next().unwrap_or_default(),
            it.next().unwrap_or_default(),
        ]
    }
}

fn canonical_uuid(value: &str) -> Result<Uuid, FileStoreError> {
    let id = Uuid::parse_str(value).map_err(|_| FileStoreError::InvalidKey)?;
    if id.hyphenated().to_string() != value {
        return Err(FileStoreError::InvalidKey);
    }
    Ok(id)
}

/// Raw ciphertext backends. Crate-private: every public path goes through [`Encrypted`].
#[async_trait::async_trait]
pub(crate) trait Backend: Send + Sync + 'static {
    fn kind(&self) -> BackendKind;
    /// Store the complete ciphertext stream; returns stored bytes. A body error
    /// is returned unchanged after cleanup.
    async fn put(&self, key: &ObjectKey, body: ByteStream) -> Result<u64, FileStoreError>;
    async fn get(&self, key: &ObjectKey) -> Result<ByteStream, FileStoreError>;
    async fn delete(&self, key: &ObjectKey) -> Result<(), FileStoreError>;
    /// Stored (ciphertext) size.
    async fn head(&self, key: &ObjectKey) -> Result<Option<u64>, FileStoreError>;
}

/// The only [`FileStore`] implementation: mandatory encryption over a backend.
pub(crate) struct Encrypted<B> {
    backend: B,
    keys: Arc<KeyRing>,
}

impl<B: Backend> Encrypted<B> {
    pub(crate) fn new(backend: B, keys: Arc<KeyRing>) -> Self {
        Self { backend, keys }
    }
    #[cfg(test)]
    pub(crate) fn backend(&self) -> &B {
        &self.backend
    }
}

fn observe<T>(
    kind: BackendKind,
    op: &'static str,
    result: Result<T, FileStoreError>,
) -> Result<T, FileStoreError> {
    crate::metrics::METRICS.observe_file_store(
        kind.as_str(),
        op,
        result.as_ref().err().map(|e| e.code()),
    );
    result
}

#[async_trait::async_trait]
impl<B: Backend> FileStore for Encrypted<B> {
    async fn put(
        &self,
        key: &ObjectKey,
        body: ByteStream,
        meta: PutMeta,
    ) -> Result<StoredObject, FileStoreError> {
        let kind = self.backend.kind();
        let (ciphertext, summary) = crypto::encrypt_stream(&self.keys, key, body, meta.max_bytes);
        let result = async {
            let stored_size = self.backend.put(key, ciphertext).await?;
            let Some(done) = summary.take() else {
                // A backend reported success without consuming the whole stream.
                let _ = self.backend.delete(key).await;
                return Err(FileStoreError::Unavailable);
            };
            if crypto::stored_len(done.size) != Some(stored_size) {
                let _ = self.backend.delete(key).await;
                return Err(FileStoreError::Unavailable);
            }
            crate::metrics::METRICS.observe_file_store_bytes(kind.as_str(), "put", done.size);
            Ok(StoredObject {
                key: key.clone(),
                size: done.size,
                sha256: done.sha256,
                key_id: self.keys.active_id().to_owned(),
                stored_size,
            })
        }
        .await;
        observe(kind, "put", result)
    }

    async fn get(&self, key: &ObjectKey) -> Result<ByteStream, FileStoreError> {
        let kind = self.backend.kind();
        let ciphertext = observe(kind, "get", self.backend.get(key).await)?;
        Ok(crypto::decrypt_stream(
            self.keys.clone(),
            key.clone(),
            ciphertext,
            kind,
        ))
    }

    async fn delete(&self, key: &ObjectKey) -> Result<(), FileStoreError> {
        observe(
            self.backend.kind(),
            "delete",
            self.backend.delete(key).await,
        )
    }

    async fn head(&self, key: &ObjectKey) -> Result<Option<ObjectInfo>, FileStoreError> {
        let result = match self.backend.head(key).await {
            Ok(None) => Ok(None),
            Ok(Some(stored)) => crypto::plaintext_len(stored)
                .map(|size| {
                    Some(ObjectInfo {
                        size,
                        stored_size: stored,
                    })
                })
                .ok_or(FileStoreError::Integrity),
            Err(e) => Err(e),
        };
        observe(self.backend.kind(), "head", result)
    }

    async fn health(&self) -> Result<StoreHealth, FileStoreError> {
        use futures::StreamExt;
        let started = std::time::Instant::now();
        let key = ObjectKey::health_probe();
        let mut probe = vec![0u8; 1024];
        crate::entropy::fill(&mut probe).map_err(|_| FileStoreError::Unavailable)?;
        let payload = Bytes::from(probe);
        let result = async {
            let body: ByteStream = futures::stream::iter([Ok(payload.clone())]).boxed();
            self.put(&key, body, PutMeta::default()).await?;
            let mut read = Vec::new();
            let mut stream = self.get(&key).await?;
            while let Some(chunk) = stream.next().await {
                read.extend_from_slice(&chunk?);
            }
            if read != payload {
                return Err(FileStoreError::Integrity);
            }
            if self.head(&key).await?.map(|i| i.size) != Some(payload.len() as u64) {
                return Err(FileStoreError::Integrity);
            }
            self.delete(&key).await?;
            if self.head(&key).await?.is_some() {
                return Err(FileStoreError::Unavailable);
            }
            Ok(())
        }
        .await;
        if result.is_err() {
            let _ = self.backend.delete(&key).await;
        }
        let result = result.map(|()| StoreHealth {
            backend: self.backend.kind(),
            key_id: self.keys.active_id().to_owned(),
            round_trip: started.elapsed(),
        });
        observe(self.backend.kind(), "health", result)
    }
}

#[cfg(all(test, feature = "integration-tests"))]
mod api_tests;
#[cfg(all(test, feature = "integration-tests"))]
mod db_tests;
#[cfg(test)]
mod tests;
