import { describe, expect, it } from "vitest";
import { canonicalSearch, dashboardHref, parseDashboardLocation } from "./locations";
import { dashboardSearch, type DashboardSearch } from "./permissions";
import { authorizedLocation, clearRememberedPortals, isAdminPage, rememberedPortal, rememberPortal, resolveDashboardSearch, scopeSearch } from "./navigation";
import { admin, session, personal, storage } from "./test-fixtures";
const pairs: [DashboardSearch, string][] = [[{ page: "platform-overview" }, "/admin"], [{ page: "users" }, "/admin/users"], [{ page: "user-detail", record: "u" }, "/admin/users/u"], [{ page: "catalog-detail", record: "c" }, "/admin/catalogs/c"], [{ page: "workspace-detail", kind: "project", record: "p" }, "/admin/projects/p"], [{ page: "workspace-detail", record: "t" }, "/admin/teams/t"], [{ page: "overview", ws: "personal" }, "/workspaces/personal"], [{ page: "keys", ws: "personal" }, "/workspaces/personal/keys"], [{ page: "grants", ws: "personal" }, "/workspaces/personal/models"], [{ page: "costs", ws: "personal" }, "/workspaces/personal/costs"], [{ page: "workspace-settings", ws: "team", tab: "limits" }, "/workspaces/team/settings?tab=limits"], [{ page: "model-detail", record: "m", tab: "routing" }, "/admin/models/m?tab=routing"], [{ page: "provider-detail", record: "p" }, "/admin/connections/p"], [{ page: "providers" }, "/admin/connections"], [{ page: "policies" }, "/admin/limits"], [{ page: "oidc" }, "/admin/sso-groups"], [{ page: "deployment-detail", record: "d", tab: "pricing" }, "/admin/routes/d?tab=pricing"], [{ page: "model-new" }, "/admin/models/new"], [{ page: "model-new", connection: "c1" }, "/admin/models/new?connection=c1"], [{ page: "models", connection: "c1" }, "/admin/models?connection=c1"], [{ page: "home" }, "/home"], [{ page: "requests", ws: "team" }, "/workspaces/team/requests"], [{ page: "profile" }, "/profile"], [{ page: "accept-invitation" }, "/invitations/accept"]];
describe("canonical enterprise dashboard locations", () => {
  it.each(pairs)("round trips %j", (search, href) => { expect(dashboardHref(search)).toBe(href); expect(parseDashboardLocation(href)).toMatchObject(search); expect(dashboardHref(parseDashboardLocation(href)!)).toBe(href); });
  it.each([["members", "members"], ["service-accounts", "service-accounts"], ["governance", "limits"], ["audit", "audit"], ["invitations", "invitations"]] as const)("preserves %s settings composition", (page, tab) => { expect(canonicalSearch({ page, ws: "team" })).toMatchObject({ page: "workspace-settings", tab }); expect(dashboardHref({ page, ws: "team" })).toBe(`/workspaces/team/settings?tab=${tab}`); });
  it("keeps platform collections in Admin and workspace settings contextual", () => { expect(isAdminPage(parseDashboardLocation("/admin/projects")!.page!)).toBe(true); expect(isAdminPage(parseDashboardLocation("/workspaces/team/settings")!.page!)).toBe(false); expect(resolveDashboardSearch({}, admin)).toMatchObject({ page: "overview", ws: "personal" }); });
  it("uses path scope, never hostile query scope", () => { expect(parseDashboardLocation("/workspaces/team/keys?ws=personal&page=providers")).toMatchObject({ page: "keys", ws: "team" }); expect(parseDashboardLocation("/admin/models?ws=personal")).toMatchObject({ page: "models", ws: undefined }); });
  it.each(["/oops", "/admin/unknown", "/admin/models/m/unknown", "/workspaces/team/members", "/api/v1/me", "//evil.invalid/admin", "https://evil.invalid/admin", "/?page=oops", "/?org=removed", "/workspaces/%2Fsecret", "/admin/models/%E0%A4%A", "/organizations/org/settings", "/admin/organizations"])("rejects removed or invalid path %s", href => expect(parseDashboardLocation(href)).toBeUndefined());
  it("whitelists query state and rejects secrets and arbitrary objects", () => { expect(dashboardSearch({ page: "deployments", q: "Model name", enabled: "false", offset: "100", token: "secret", credential_ref: {} })).toEqual({ page: "deployments", ws: undefined, q: "Model name", enabled: "false", offset: 100 }); expect(dashboardSearch({ enabled: "maybe", offset: -1, tab: "secret", record: "bad/record", q: "x".repeat(201) })).toEqual({ page: undefined, ws: undefined }); expect(dashboardHref({ ...({ token: "secret" } as object), page: "profile" })).toBe("/profile"); });
  it("bounds query lengths and offsets", () => { expect(dashboardSearch({ q: "x".repeat(200), offset: 100000 })).toMatchObject({ q: "x".repeat(200), offset: 100000 }); expect(dashboardSearch({ offset: 100001 }).offset).toBeUndefined(); });
  it("round trips nested limits and report filters without API-scope changes", () => { const state: DashboardSearch = { page: "workspace-settings", ws: "team", tab: "limits", scope: "workspace", view: "inherited" }; expect(parseDashboardLocation(dashboardHref(state))).toMatchObject(state); expect(dashboardHref({ page: "workspace-settings", ws: "team", tab: "limits", scope: "keys", record: "key-id" })).toBe("/workspaces/team/keys/key-id"); expect(dashboardHref({ page: "workspace-settings", ws: "team", tab: "limits", scope: "keys" })).toBe("/workspaces/team/keys"); expect(scopeSearch("keys", "personal")).toEqual({ page: "keys", ws: "personal" }); });
});
describe("legacy admin URLs redirect", () => {
  it("sends /admin/routing and /admin/deployments to Models and old route records to /admin/routes", () => {
    expect(parseDashboardLocation("/admin/routing")).toEqual({ page: "models" });
    expect(parseDashboardLocation("/admin/deployments?q=x")).toEqual({ page: "models" });
    expect(dashboardHref({ page: "routing" })).toBe("/admin/models"); expect(dashboardHref({ page: "deployments" })).toBe("/admin/models");
    const old = parseDashboardLocation("/admin/deployments/d1?tab=pricing");
    expect(old).toMatchObject({ page: "deployment-detail", record: "d1", tab: "pricing" });
    expect(dashboardHref(old!)).toBe("/admin/routes/d1?tab=pricing");
  });
});
describe("renamed admin URLs (rule 10)", () => {
  it.each([["/admin/providers", "providers", "/admin/connections"], ["/admin/policies", "policies", "/admin/limits"], ["/admin/oidc", "oidc", "/admin/sso-groups"], ["/admin/providers/c1", "provider-detail", "/admin/connections/c1"]] as const)("opens %s and rewrites it", (old, page, now) => {
    const parsed = parseDashboardLocation(old); expect(parsed?.page).toBe(page); expect(dashboardHref(parsed!)).toBe(now);
  });
});
describe("model setup locations", () => {
  it("routes Add model as a platform page, not a model record named new", () => { expect(parseDashboardLocation("/admin/models/new")).toMatchObject({ page: "model-new", record: undefined }); expect(isAdminPage("model-new")).toBe(true); expect(authorizedLocation({ page: "model-new" }, session)).toBe(false); expect(authorizedLocation({ page: "model-new" }, admin)).toBe(true); });
  it("accepts only identifier-shaped connection filters", () => { expect(dashboardSearch({ connection: "c1" }).connection).toBe("c1"); expect(dashboardSearch({ connection: "../evil" }).connection).toBeUndefined(); const hostile = parseDashboardLocation("/admin/models/new?connection=%2Fevil"); expect(hostile?.page).toBe("model-new"); expect(hostile?.connection).toBeUndefined(); });
});
describe("authorized portal history", () => {
  it("does not replace an explicit unavailable workspace with private defaults", () => { const missing = resolveDashboardSearch({ page: "overview", ws: "missing" }, admin); expect(missing.ws).toBe("missing"); expect(authorizedLocation(missing, admin)).toBe(false); });
  it("records metadata only and isolates users", () => { const store = storage(); rememberPortal(store, admin, { page: "keys", ws: "personal", q: "sensitive text", offset: 200 }); expect([...store.entries.values()]).toEqual(["/workspaces/personal/keys"]); expect(rememberedPortal(store, admin, "workspace")).toMatchObject({ page: "keys", ws: "personal" }); expect(rememberedPortal(store, { ...admin, user: { ...admin.user, id: "other" } }, "workspace")).toBeUndefined(); });
  it("revalidates inventory and authority against fresh /me", () => { const store = storage(); rememberPortal(store, admin, { page: "models" }); expect(rememberedPortal(store, session, "admin")).toBeUndefined(); rememberPortal(store, admin, { page: "keys", ws: "personal" }); expect(rememberedPortal(store, { ...admin, workspaces: [] }, "workspace")).toBeUndefined(); expect(store.length).toBe(0); });
  it("clears all gateway context on logout without unrelated storage", () => { const store = storage(); rememberPortal(store, admin, { page: "models" }); rememberPortal(store, admin, { page: "overview", ws: "team" }); store.setItem("unrelated", "keep"); clearRememberedPortals(store); expect([...store.entries]).toEqual([["unrelated", "keep"]]); });
  it.each(["//evil.invalid/admin", "/admin/unknown", "/profile", "/admin/models", "/workspaces/foreign/keys"])("forgets malformed or cross-portal destination %s", href => { const store = storage(); store.setItem("omg:enterprise:portal:me:workspace", href); expect(rememberedPortal(store, admin, "workspace")).toBeUndefined(); expect(store.length).toBe(0); });
  it("rejects foreign personal remembered scopes even if a malformed inventory includes them", () => { const actor = { ...admin, workspaces: [{ ...personal, owner_user_id: "other" }] }; expect(authorizedLocation({ page: "keys", ws: "personal" }, actor)).toBe(false); });
});
