import { afterEach, describe, expect, it, vi } from "vitest";
import { dateError, utcMonth, reportPeriod, reportQuery, reportFields, formatCount, exactDifference, trendPoints, reconciliationFields, reconciliationBody } from "./reports";
import { priceBody, priceFields, policyFields, type Cost } from "./governance";
import { validateFields } from "./forms";
import { report } from "./test-fixtures";
const uuid = "00000000-0000-0000-0000-000000000001";
afterEach(() => { vi.useRealTimers(); });
describe("exclusive UTC report periods", () => {
  it("defaults through tomorrow UTC rather than inclusive today", () => expect(utcMonth(new Date("2026-08-10T23:59:59-04:00"))).toEqual({ start_date: "2026-08-01", end_date: "2026-08-12" }));
  it.each(["2026-02-30", "2026-13-01", "2026-01-00", "26-01-01", "2026-01-01T00:00:00Z"])("rejects invalid calendar date %s", d => expect(dateError(d)).toBeDefined());
  it("allows leap days and exactly 1 to 93 exclusive UTC days", () => { expect(dateError("2024-02-29")).toBeUndefined(); expect(reportPeriod({ start_date: "2026-01-01", end_date: "2026-01-02" }, new Date("2026-08-10"))).toEqual({ start_date: "2026-01-01", end_date: "2026-01-02" }); expect(() => reportPeriod({ start_date: "2026-01-01", end_date: "2026-04-04" }, new Date("2026-08-10"))).not.toThrow(); });
  it.each([["2026-01-01", "2026-01-01"], ["2026-01-02", "2026-01-01"], ["2026-01-01", "2026-04-05"], ["2026-08-10", "2026-08-12"]])("rejects empty/reversed/long/future period %s..%s", (start_date, end_date) => expect(() => reportPeriod({ start_date, end_date }, new Date("2026-08-10"))).toThrow());
  it("compares equal exclusive periods and rejects supported-date underflow", () => { expect(reportQuery({ start_date: "2026-01-01", end_date: "2026-01-02", compare: "previous_period" }, true)).toContain("compare=previous_period"); expect(() => reportQuery({ start_date: "0001-01-01", end_date: "0001-01-02", compare: "previous_period" }, true)).toThrow("underflows"); });
  it("applies all dimensions to the same report and does not leak private dimensions", () => { const query = new URLSearchParams(reportQuery({ start_date: "2026-01-01", end_date: "2026-01-02", model: "alias", provider: "openai", workspace_id: uuid, cost_center_id: "unallocated", actor_user_id: uuid, accounting_status: "unknown" }, true)); expect(Object.fromEntries(query)).toMatchObject({ model: "alias", provider: "openai", workspace_id: uuid, cost_center_id: "unallocated", actor_user_id: uuid, accounting_status: "unknown" }); expect(() => reportQuery({ ws: "one", workspace_id: uuid }, false)).toThrow("must match"); expect(() => reportQuery({ service_account_id: uuid }, true)).toThrow("private"); });
  it("discovers filter choices from authorized aggregate dimensions only", () => { const fields = reportFields({}, { ...report, breakdowns: { ...report.breakdowns, workspaces: [{ id: uuid, name: "Authorized personal total", totals: report.totals }] } }, true); expect(fields.find(f => f.name === "workspace_id")?.options).toEqual([{ value: uuid, label: "Authorized personal total" }]); expect(fields.some(f => f.name === "service_account_id")).toBe(false); });
});
describe("exact reporting and cache reconciliation", () => {
  it("formats decimal-string counters exactly above safe integers", () => { expect(formatCount("9007199254740993")).toBe("9,007,199,254,740,993"); expect(formatCount(null)).toBe("Unknown"); expect(formatCount(Number("9007199254740993"))).toBe("Unknown"); expect(exactDifference("9007199254740993", "9007199254740992")).toBe("+1"); expect(exactDifference("1", "2", true)).toBe("−$0.000001"); });
  it("converts only bounded normalized chart coordinates to numbers", () => { const daily = [{ date: "2026-01-01", totals: { ...report.totals, known_cost_microusd: "1000000000000000000000000000000" } }, { date: "2026-01-02", totals: { ...report.totals, known_cost_microusd: "1" } }]; const points = trendPoints({ ...report, daily }); expect(points[0].values.known).toBe(100); expect(points[0].label).toContain("$1,000,000,000,000,000,000,000,000.00"); expect(points[1].label).toContain("$0.000001"); });
  it("preserves every pinned raw and normalized observation", () => { const cost = { input_tokens: "9007199254740993", output_tokens: "0", billing_usage: { ...report.billing_usage, cache_write_5m_input_tokens: "9" } } as Cost, fields = reconciliationFields(cost); expect(validateFields(fields, { input_tokens: "9007199254740992", output_tokens: "0", evidence: "receipt:1" }).input_tokens).toContain("Preserve"); expect(validateFields(fields, { input_tokens: "9007199254740993", output_tokens: "0", cache_write_5m_input_tokens: "8", evidence: "receipt:1" }).cache_write_5m_input_tokens).toContain("Preserve"); const body = reconciliationBody({ input_tokens: "9007199254740993", output_tokens: "0", total_input_tokens: "15", uncached_input_tokens: "1", cache_read_input_tokens: "2", cache_write_input_tokens: "12", cache_write_default_input_tokens: "0", cache_write_5m_input_tokens: "9", cache_write_1h_input_tokens: "3", evidence: "receipt:1" }); expect(body.billing_usage).toMatchObject({ cache_write_input_tokens: "12", cache_write_5m_input_tokens: "9", cache_write_1h_input_tokens: "3", cache_write_default_input_tokens: "0" }); });
  it("cannot clear a previously stored local cap even when masked by a platform ceiling", () => { const local = { requests_per_minute: 100, tokens_per_minute: null, concurrent_requests: null, monthly_budget_microusd: "100000000" }, platform = { ...local, requests_per_minute: 10, monthly_budget_microusd: "10000000" }; expect(validateFields(policyFields(local, platform, true), {})).toHaveProperty("requests_per_minute"); expect(validateFields(policyFields(local, platform, true), {})).toHaveProperty("monthly_budget_usd"); expect(validateFields(policyFields(local, undefined, false), {})).toEqual({}); expect(validateFields(policyFields(local, undefined, true), { requests_per_minute: "101", monthly_budget_usd: "101" })).toHaveProperty("requests_per_minute"); expect(validateFields(policyFields(local, undefined, true), { requests_per_minute: "101", monthly_budget_usd: "101" })).toHaveProperty("monthly_budget_usd"); });
  it("keeps missing counts null, never synthesized zero", () => { expect(reconciliationBody({ input_tokens: "1", output_tokens: "0", evidence: "receipt:1" }).billing_usage).toBeNull(); expect(reconciliationBody({ input_tokens: "1", output_tokens: "0", cache_read_input_tokens: "0", evidence: "receipt:1" }).billing_usage?.cache_read_input_tokens).toBe("0"); });
  it("publishes v2 unknown, explicit free and not-applicable cache rates distinctly", () => { const values = { input_usd_per_million: "0", output_usd_per_million: "0", input_token_limit: "10", output_token_limit: "0", cache_read_status: "priced", cache_read_usd: "0", cache_write_status: "unknown", cache_write_5m_status: "not_applicable", cache_write_1h_status: "unknown" }; expect(validateFields(priceFields(), values)).toEqual({}); expect(priceBody(values)).toMatchObject({ pricing_version: 2, output_token_limit: 0, cache_pricing: { read: { status: "priced", microusd_per_million: "0" }, write: { status: "unknown" }, write_5m: { status: "not_applicable" } } }); });
});
