import { describe, expect, it } from "vitest";
import { jumpTargets } from "./search";
import { session, admin, auditor, personal, team, project, member } from "./test-fixtures";
describe("permission-scoped jump search", () => {
  it("does not offer platform destinations to ordinary members", () => { const ids = jumpTargets({ ...session, workspaces: [member, personal] }, personal).map(t => t.id); expect(ids).toContain("page:keys"); for (const page of ["users", "platform-teams", "oidc", "models", "policies"]) expect(ids).not.toContain(`page:${page}`); });
  it("offers contextual settings to shared admins, not platform administration", () => { const targets = jumpTargets(session, team); expect(targets.map(t => t.id)).toContain("page:workspace-settings"); expect(targets.map(t => t.id)).not.toContain("page:users"); });
  it("personal ownership does not grant global administration", () => { expect(jumpTargets(session, personal).map(t => t.id)).not.toContain("page:users"); });
  it.each([admin, auditor])("uses platform destinations without leftover workspace scope", actor => { const targets = jumpTargets(actor, personal); for (const page of ["catalogs", "platform-teams", "users"] as const) expect(targets.find(t => t.id === `page:${page}`)?.search).toEqual({ page, ws: undefined }); });
  it("jumps among sibling authorized contexts, without invented hierarchy", () => { const targets = jumpTargets(session, personal); expect(targets.find(t => t.id === `workspace:${project.id}`)?.search).toEqual({ page: "overview", ws: project.id }); expect(targets.filter(t => t.group === "Personal")).toHaveLength(1); expect(new Set(targets.map(t => t.id)).size).toBe(targets.length); });
  it("offers Home and the selected workspace's pages, and only real memberships", () => { const staff = { ...project, role: null, membership_source: null }, actor = { ...admin, workspaces: [personal, team, staff] }, targets = jumpTargets(actor, team); expect(targets.find(t => t.id === "page:home")?.search).toEqual({ page: "home", ws: undefined }); expect(targets.find(t => t.id === "page:requests")).toMatchObject({ hint: "Product", search: { page: "requests", ws: "team" } }); expect(targets.find(t => t.id === "page:workspace-settings")?.label).toBe("Settings"); expect(targets.map(t => t.id)).not.toContain("workspace:project"); expect(targets.find(t => t.id === "workspace:team")?.hint).toBe("Team · Admin"); expect(jumpTargets(actor, staff).map(t => t.id)).not.toContain("page:keys"); });
  it("never hydrates foreign personal metadata from global search", () => { const targets = jumpTargets({ ...admin, workspaces: [...admin.workspaces, { ...personal, id: "foreign", owner_user_id: "other" }] }); expect(targets.map(t => t.id)).not.toContain("workspace:foreign"); });
  it("supports account destinations without any workspace or invented resources", () => { expect(jumpTargets({ ...session, workspaces: [] }).map(t => t.id)).toEqual(["page:home", "page:profile"]); });
  it("offers Add model to Platform Admins only and finds old names", () => { const ids = (actor: typeof admin) => jumpTargets(actor).map(t => t.id); expect(ids(admin)).toContain("page:model-new"); expect(ids(auditor)).not.toContain("page:model-new"); expect(ids(session)).not.toContain("page:model-new"); for (const legacy of ["page:deployments", "page:routing"]) expect(ids(admin)).not.toContain(legacy); const connections = jumpTargets(admin).find(t => t.id === "page:providers"); expect(connections?.label).toBe("Connections"); expect(connections?.keywords).toContain("provider connections"); });
});
