import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { renderToStaticMarkup } from "react-dom/server";
import type { ReactNode } from "react";
import { ActionProvider } from "../components/ui";
import type { CostReport } from "./governance";
import type { Session, Workspace, Model, Provider, Grant } from "./api";
export const full = { issue_own_key: true, manage_members: true, manage_service_accounts: true, delegate_models: true, manage_policy: true, view_all_activity: true };
export const none = { issue_own_key: false, manage_members: false, manage_service_accounts: false, delegate_models: false, manage_policy: false, view_all_activity: false };
export const personal: Workspace = { id: "personal", name: "Personal", kind: "personal", owner_user_id: "me", role: "owner", membership_source: "manual", capabilities: { ...full, manage_members: false, manage_service_accounts: false } };
export const team: Workspace = { id: "team", name: "Product", kind: "team", owner_user_id: null, role: "admin", membership_source: "manual", capabilities: full };
export const project: Workspace = { ...team, id: "project", name: "Research", kind: "project" };
export const session: Session = { installation: { id: "installation", name: "Example gateway" }, user: { id: "me", email: "me@example.invalid", platform_role: "user" }, workspaces: [personal, team, project], capabilities: { platform_read: false, platform_write: false, create_workspace: false } };
export const admin: Session = { ...session, user: { ...session.user, platform_role: "admin" }, capabilities: { platform_read: true, platform_write: true, create_workspace: true } };
export const auditor: Session = { ...admin, user: { ...session.user, platform_role: "auditor" }, capabilities: { platform_read: true, platform_write: false, create_workspace: false }, workspaces: [personal] };
export const member: Workspace = { ...team, role: "member", capabilities: { ...none, issue_own_key: true } };
export const model: Model = { id: "model", public_name: "company/smart", display_name: "Smart model", enabled: true, supported_protocols: ["chat_completions"] };
export const provider: Provider = { id: "provider", name: "Production provider", provider: "openai", endpoint: null, region: null, enabled: false, auth_mode: "credential" };
export const grant: Grant = { model_id: model.id, public_name: model.public_name, display_name: model.display_name, enabled: true, selected: true, catalog_granted: true, direct_granted: false, available_from_catalog: true, supported_protocols: model.supported_protocols };
export const policy = { requests_per_minute: null, tokens_per_minute: null, concurrent_requests: null, monthly_budget_microusd: null };
export const report: CostReport = { period: { start_date: "2026-01-01", end_date: "2026-01-02", timezone: "UTC", includes_partial_day: false }, scope: "workspace", observed_at: "2026-01-02T00:00:00Z", basis: "configured_rate_estimate", currency: "USD", totals: { known_cost_microusd: "9007199254740993", held_microusd: "1", attempts: "12", root_requests: "10", unresolved_attempts: "3" }, health: { pending_attempts: "1", unknown_attempts: "2", missing_reservation_attempts: "1", unpriced_attempts: "1", aged_hold_attempts: "1", unbounded_attempts: "1" }, daily: [], breakdowns: { models: [], providers: [], workspaces: [], cost_centers: [], service_accounts: [] }, comparison: null, coverage: { priced_attempts: "5", settled_attempts: "9", total_attempts: "12", complete_billing_attempts: "6", legacy_pricing_attempts: "1", incomplete_billing_attempts: "6" }, cost_components: { uncached_input_microusd: "0", cache_read_microusd: "0", cache_write_default_microusd: "0", cache_write_5m_microusd: "0", cache_write_1h_microusd: "0", output_microusd: "0", legacy_microusd: "9007199254740993" }, billing_usage: { total_input_tokens: null, uncached_input_tokens: null, cache_read_input_tokens: null, cache_write_input_tokens: null, cache_write_default_input_tokens: null, cache_write_5m_input_tokens: null, cache_write_1h_input_tokens: null }, breakdowns_truncated: false };
export function storage() { const entries = new Map<string, string>(); return { entries, get length() { return entries.size; }, key: (i: number) => [...entries.keys()][i] ?? null, setItem: (key: string, value: string) => { entries.set(key, value); }, getItem: (key: string) => entries.get(key) ?? null, removeItem: (key: string) => { entries.delete(key); } }; }
export function testClient() { return new QueryClient({ defaultOptions: { queries: { retry: false, retryOnMount: false, staleTime: Infinity, gcTime: 0 } } }); }
export function markup(node: ReactNode, entries: [string, unknown][] = [], client = testClient()) { for (const [path, data] of entries) client.setQueryData(["api", undefined, path], data); const html = renderToStaticMarkup(<QueryClientProvider client={client}><ActionProvider>{node}</ActionProvider></QueryClientProvider>); return html; }
