import { afterEach, describe, expect, it, vi } from "vitest";
import { EXPORT_MAX_BYTES, usageCsv } from "./usage-export";
const dates = "start_date=2026-01-01&end_date=2026-01-02";
afterEach(() => vi.unstubAllGlobals());
describe("bounded same-origin filtered CSV export", () => {
  it("uses fixed encoded workspace paths, exclusive dates, cookies, no cache and no redirects", async () => { const fetch = vi.fn().mockResolvedValue(new Response("id,cost\r\nrow,1\r\n", { headers: { "content-type": "text/csv; charset=utf-8" } })); vi.stubGlobal("fetch", fetch); const controller = new AbortController(), blob = await usageCsv("team/name", 100, 100, controller.signal, dates); expect(fetch).toHaveBeenCalledWith(`/api/v1/workspaces/team%2Fname/usage-export?${dates}&limit=100&offset=100`, expect.objectContaining({ credentials: "same-origin", cache: "no-store", redirect: "error", signal: controller.signal })); expect(await blob.text()).toContain("row,1"); });
  it("rejects unbounded pagination without fetching", async () => { const fetch = vi.fn(); vi.stubGlobal("fetch", fetch); for (const [limit, offset] of [[0, 0], [1001, 0], [1, -1], [1, 100001], [1.5, 0]]) await expect(usageCsv("ws", limit, offset, undefined, dates)).rejects.toThrow("Invalid export page"); expect(fetch).not.toHaveBeenCalled(); });
  it("requires explicit date bounds", async () => { const fetch = vi.fn(); vi.stubGlobal("fetch", fetch); await expect(usageCsv("ws", 1, 0)).rejects.toThrow("explicit UTC period"); expect(fetch).not.toHaveBeenCalled(); });
  it("never downloads HTML login/error content", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response("<html>Login</html>", { headers: { "content-type": "text/html" } }))); await expect(usageCsv("ws", 1, 0, undefined, dates)).rejects.toThrow("did not return CSV"); });
  it("bounds streamed bytes even without Content-Length", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response(new Uint8Array(EXPORT_MAX_BYTES + 1), { headers: { "content-type": "text/csv" } }))); await expect(usageCsv("ws", 1000, 0, undefined, dates)).rejects.toThrow("exceeds 10 MiB"); });
  it("surfaces authorization failures without saving server text", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response("private server contents", { status: 403 }))); await expect(usageCsv("ws", 1, 0, undefined, dates)).rejects.toThrow("CSV export failed (403)"); });
  it("clears session memory after expired authentication", async () => { const dispatchEvent = vi.fn(); vi.stubGlobal("window", { dispatchEvent }); vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response("", { status: 401 }))); await expect(usageCsv("ws", 1, 0, undefined, dates)).rejects.toThrow(); expect(dispatchEvent).toHaveBeenCalledWith(expect.objectContaining({ type: "omg:unauthorized" })); });
});
