import { describe, expect, it } from "vitest";
import { canView } from "./permissions";
import { dashboardHref } from "./locations";
import { clearRememberedPortals, contextOptions, landingSearch, portalWorkspaces, rememberedWorkspace, rememberWorkspace, resolveDashboardSearch, scopeSearch, sidebarWorkspace, workspaceSections } from "./navigation";
import { member, none, auditor } from "./test-fixtures";
import { session, admin, personal, team, project, storage } from "./test-fixtures";
describe("two-level Workspace portal sidebar", () => {
  const labels = (actor: typeof session, ws?: typeof team) => workspaceSections(actor, ws).map(s => [s.label, s.items.map(i => i.label)]);
  it("puts Home in a user-level group and the selected workspace's pages in a group named after it", () => {
    expect(labels(session, personal)).toEqual([["Workspace", ["Home"]], ["Personal", ["Overview", "Models", "API keys", "Logs", "Files", "Usage & costs", "Settings"]]]);
    expect(labels(session, project)).toEqual([["Workspace", ["Home"]], ["Research", ["Overview", "Models", "API keys", "Logs", "Files", "Usage & costs", "Settings"]]]);
    expect(labels({ ...session, workspaces: [personal, member] }, member)[1]).toEqual(["Product", ["Overview", "Models", "API keys", "Logs", "Files", "Usage & costs", "Settings"]]);
    expect(labels({ ...session, workspaces: [] })).toEqual([["Workspace", ["Home"]]]);
  });
  it("never shows a non-member shared workspace, even to Platform Admins", () => { const staff = { ...project, role: null, membership_source: null, capabilities: { ...none, manage_members: true, manage_service_accounts: true, view_all_activity: true } }, actor = { ...admin, workspaces: [personal, team, staff] }; expect(portalWorkspaces(actor).map(w => w.id)).toEqual(["personal", "team"]); expect(contextOptions(actor).flatMap(g => g.items.map(i => i.ws))).toEqual(["personal", "team"]); expect(labels(actor, staff)).toEqual([["Workspace", ["Home"]]]); expect(canView("overview", actor, staff)).toBe(false); expect(canView("workspace-settings", actor, staff)).toBe(false); expect(sidebarWorkspace(actor, {}, staff)).toEqual(personal); });
  it("lands on Home with Personal selected and keeps Home user-level", () => { const store = storage(); rememberWorkspace(store, session, { page: "overview", ws: "team" }); expect(landingSearch(session, store)).toEqual({ page: "home" }); expect(rememberedWorkspace(store, session)).toEqual(personal); expect(resolveDashboardSearch({ page: "home", ws: "team" }, session)).toEqual({ page: "home", ws: undefined }); expect(scopeSearch("home", "team")).toEqual({ page: "home", ws: undefined }); expect(canView("home", { ...auditor, workspaces: [] })).toBe(true); const none2 = storage(); expect(landingSearch({ ...session, workspaces: [team] }, none2)).toEqual({ page: "home" }); expect(none2.length).toBe(0); });
});
describe("sibling workspace context beside settings", () => {
  it("keeps the full sidebar canonically linked to the selected workspace", () => { const context = sidebarWorkspace(session, { page: "workspace-settings" }, team); const [user, selected] = workspaceSections(session, context); expect(user.items.map(n => dashboardHref(scopeSearch(n.page, context?.id)))).toEqual(["/home"]); expect(selected.label).toBe("Product"); expect(selected.items.filter(n => canView(n.page, session, context)).map(n => dashboardHref(scopeSearch(n.page, context?.id)))).toEqual(["/workspaces/team", "/workspaces/team/models", "/workspaces/team/keys", "/workspaces/team/logs", "/workspaces/team/files", "/workspaces/team/costs", "/workspaces/team/settings"]); });
  it("groups Personal, Teams and Projects with no inferred hierarchy", () => { expect(contextOptions(session).map(g => g.label)).toEqual(["Personal", "Teams", "Projects"]); expect(contextOptions(session)[2].items[0].workspace).toEqual(project); });
  it("remembers shared context across settings tabs and reloads, metadata only", () => { const store = storage(); for (const ws of [team, project]) { rememberWorkspace(store, session, { page: "keys", ws: ws.id, record: "private-key", q: "sensitive" }); expect([...store.entries.values()]).toEqual([ws.id]); expect(sidebarWorkspace(session, { page: "workspace-settings" }, rememberedWorkspace(store, session))).toEqual(ws); } });
  it("defaults to an accessible private or shared workspace", () => { expect(sidebarWorkspace(session, { page: "overview" })).toEqual(personal); expect(sidebarWorkspace({ ...session, workspaces: [team, project] }, { page: "overview" })).toEqual(team); });
  it("isolates context by identity and never selects foreign personal metadata", () => { const store = storage(); rememberWorkspace(store, session, { page: "overview", ws: "team" }); expect(rememberedWorkspace(store, { ...session, user: { ...session.user, id: "another" } })).toBeUndefined(); const foreign = { ...personal, id: "foreign", owner_user_id: "other" }; expect(sidebarWorkspace({ ...admin, workspaces: [foreign] }, {}, foreign)).toBeUndefined(); expect(contextOptions({ ...admin, workspaces: [foreign] })).toEqual([]); });
  it("drops revoked or disabled inventory and clears all context on logout", () => { const store = storage(); rememberWorkspace(store, session, { page: "overview", ws: "team" }); expect(rememberedWorkspace(store, { ...session, workspaces: [personal] })).toBeUndefined(); expect(store.length).toBe(0); rememberWorkspace(store, session, { page: "overview", ws: "personal" }); expect(rememberedWorkspace(store, { ...session, workspaces: [{ ...personal, disabled_at: "now" }] })).toBeUndefined(); store.setItem("unrelated", "keep"); clearRememberedPortals(store); expect([...store.entries]).toEqual([["unrelated", "keep"]]); });
  it("never substitutes remembered context for explicitly unavailable workspaces", () => { expect(sidebarWorkspace(session, { page: "keys", ws: "missing" }, team)).toBeUndefined(); expect(sidebarWorkspace(session, { page: "keys", ws: "personal" }, team)).toEqual(personal); });
  it("cannot restore absent private workspaces from stale metadata", () => { expect(sidebarWorkspace({ ...session, workspaces: [team] }, {}, personal)).toEqual(team); });
  it("ignores invalid writes and tolerates disabled storage", () => { const store = storage(); for (const search of [{ page: "keys" as const, ws: "missing" }, { page: "models" as const, ws: "team" }, { page: "profile" as const, ws: "team" }]) rememberWorkspace(store, session, search); expect(store.length).toBe(0); const blocked = { getItem() { throw new Error("disabled"); }, setItem() { throw new Error("disabled"); }, removeItem() { throw new Error("disabled"); } }; expect(() => rememberWorkspace(blocked, session, { page: "keys", ws: "team" })).not.toThrow(); expect(rememberedWorkspace(blocked, session)).toBeUndefined(); });
});
